from string import punctuation

# cleaning data
fileref = open('climate_tweets.csv')
lines = fileref.readlines()
# header = lines[0]
# field_names = header.strip().split(',')
lines_2 = []
print(lines)
for line in lines:
    words = line.strip().split(',')
    words[1] = ','.join(words[1:-1])
    lines_2.append(words)

# just_tweets = []
# for line in lines_2:
# just_tweets.append(line[1])
# just_tweets_no_punct = []

outfile = open('all_data_no_punct.csv', 'w')
all_data = []
print(lines_2)
for lst in lines_2:
    for char in lst[1]:
        if char in punctuation:
            lst[1] = lst[1].replace(char, "")
    lst[1] = lst[1].lower()
    all_data.append(lst)
    row_string = '{},{},{}'.format(lst[0], lst[1], lst[2])
    outfile.write(row_string)
    outfile.write('\n')
print(all_data)

# denial anc existence dictionaries, remove stopwords
existence = {}
existence_lst = []
denial = {}
denial_lst = []
total = {}

fileref = open('all_data_no_punct.csv')
lines = fileref.readlines()
# header = lines[0]
# field_names = header.strip().split(',')
for line in lines:
    words = line.strip().split(',')
    if words[2] == 'Y':
        existence_lst.append(words[1])
    elif words[2] == 'N':
        denial_lst.append(words[1])
print(existence_lst)

stopwords = {'the', 'to', 'of', 'a', 'ourselves', 'hers', 'between', 'yourself', 'but', 'again', 'there', 'about',
             'once', 'during', 'out', 'very', 'having', 'with', 'they', 'own', 'an', 'be', 'some', 'for', 'do', 'its',
             'yours', 'such', 'into', 'of', 'most', 'itself', 'other', 'off', 'is', 's', 'am', 'or', 'who', 'as',
             'from', 'him', 'each', 'the', 'themselves', 'until', 'below', 'are', 'we', 'these', 'your', 'his',
             'through', 'don', 'nor', 'me', 'were', 'her', 'more', 'himself', 'this', 'down', 'should', 'our', 'their',
             'while', 'above', 'both', 'up', 'to', 'ours', 'had', 'she', 'all', 'no', 'when', 'at', 'any', 'before',
             'them', 'same', 'and', 'been', 'have', 'in', 'will', 'on', 'does', 'yourselves', 'then', 'that', 'because',
             'what', 'over', 'why', 'so', 'can', 'did', 'not', 'now', 'under', 'he', 'you', 'herself', 'has', 'just',
             'where', 'too', 'only', 'myself', 'which', 'those', 'i', 'after', 'few', 'whom', 't', 'being', 'if',
             'theirs', 'my', 'against', 'a', 'by', 'doing', 'it', 'how', 'further', 'was', 'here', 'than'}

for tweet in existence_lst:
    words = tweet.split()
    for word in words:
        if word not in existence:
            existence[word] = 1
        else:
            existence[word] += 1
for tweet in denial_lst:
    words = tweet.split()
    for word in words:
        if word not in denial:
            denial[word] = 1
        else:
            denial[word] += 1
existence = sorted(existence.items(), key=lambda item: item[1], reverse=True)
denial = sorted(denial.items(), key=lambda item: item[1], reverse=True)
existence = dict(existence)
denial = dict(denial)

for word in existence:
    if word in stopwords:
        del existence[word]
for word in denial:
    if word in stopwords:
        del denial[word]

for word in existence:
    if word in denial:
        total[word] = existence[word] + denial[word]

total = sorted(total.items(), key=lambda item: item[1], reverse=True)
total = dict(total)

print(existence)
print(denial)
print(total)

# predicting sentiment of tweets

# fileref = open('climate_test.csv')
# tweets_out = open('cleaned_test_tweets.csv', 'w')
# lines = fileref.readlines()
# tweets = []
# lines_2 = []
# for line in lines:
#    words = line.strip().split(',')
#    words[1] = ','.join(words[1:len(words)])
#    del words[2:]
#    lines_2.append(words)
# print(lines_2)

# for line in lines_2:
#    tweets.append(line[1])
# print(tweets)
# import string
# tweets_clean = []
# for tweet in tweets:
#    for char in tweet:
#        if char in string.punctuation:
#            tweet = tweet.replace(char, "")
#    tweet = tweet.lower()
# tweet = tweet.split()
#    tweets_clean.append(tweet)
#    tweets_out.write(tweet)
#    tweets_out.write('\n')
# print(tweets_clean)

tweets_clean = open('cleaned_test_tweets.csv')
existence = {'climate': 587, 'change': 565, 'global': 450, 'warming': 414, 'link': 224, 'rt': 156, 'via': 70, 'us': 59,
             'report': 48, 'could': 47, 'worse': 44, 'allergies': 39, 'help': 36, 'green': 36, 'fight': 36, 'new': 35,
             'impacts': 31, 'action': 31, 'news': 31, 'wildlife': 30, 'effects': 27, 'stop': 27, 'take': 27,
             'energy': 27, 'makes': 27, 'à': 25, 'world': 25, 'arctic': 24, 'earth': 24, 'protect': 24, 'time': 24,
             'habitat': 23, 'may': 23, 'air': 22, 'africa': 22, 'carbon': 22, 'scientists': 21, 'science': 21,
             'blame': 21, 'real': 20, 'climatechange': 19, 'water': 19, 'bill': 18, 'day': 18, 'health': 18,
             'newsweek': 18, 'save': 18, 'dc': 18, 'weather': 17, 'environmental': 17, 'deniers': 17, 'one': 17,
             'ocean': 17, 'reduce': 17, 'thing': 16, 'good': 16, 'epa': 15, 'saveterra': 15, 'causes': 15,
             'forests': 15, 'winter': 14, 'must': 14, 'important': 14, 'think': 14, 'blizzards': 14, 'snowstorm': 14,
             'around': 13, 'future': 13, 'tackle': 13, 'national': 13, 'ever': 13, 'fighting': 12, 'sign': 12,
             'look': 12, 'cost': 12, 'get': 12, 'volcano': 12, 'volcanic': 12, 'peoples': 12, 'kills': 12, 'places': 12,
             'evidence': 11, 'like': 11, 'feel': 11, 'people': 11, 'earthday': 11, 'combat': 11, 'fronts': 11,
             'environment': 11, 'allergy': 11, 'post': 11, 'reuters': 11, 'shows': 11, 'way': 11, 'blog': 11,
             'obama': 11, 'plants': 11, 'due': 11, 'dont': 11, 'legislation': 11, 'getting': 11, 'see': 11,
             'greenpeace': 11, 'colorado': 11, 'cleaner': 10, 'part': 10, 'p2': 10, 'sierraclub': 10,
             'httpbitly9ogdyi': 10, 'threat': 10, 'rain': 10, 'solutions': 10, 'speed': 10, 'far': 10, 'gas': 10,
             'check': 10, 'tcot': 10, 'need': 10, 'vulnerable': 10, 'study': 10, 'level': 9, '10': 9, 'act': 9,
             'case': 9, 'message': 9, 'iceland': 9, 'natural': 9, 'issues': 9, 'snow': 9, 'faster': 9, 'make': 9,
             'offsets': 9, 'coast': 9, 'glacier': 9, 'season': 9, 'volcanoes': 9, 'conference': 9, 'live': 9,
             'increase': 9, 'melt': 9, 'across': 9, 'waiting': 8, 'causing': 8, 'nations': 8, 'indicators': 8,
             'security': 8, 'migration': 8, 'spring': 8, 'state': 8, 'likely': 8, 'making': 8, 'raise': 8, 'read': 8,
             'heat': 8, 'proof': 8, 'better': 8, 'intensifying': 8, 'o': 8, 'analysis': 8, 'impact': 8, 'saltiness': 8,
             'species': 8, 'invasive': 8, 'increasing': 8, 'economy': 8, 'great': 8, 'threatens': 8, 'forest': 8,
             'americas': 8, 'needed': 8, 'going': 8, 'trees': 8, 'p': 8, 'ice': 8, 'endangered': 8, 'planet': 8,
             'ground': 7, 'tired': 7, 'coalition': 7, 'grapes': 7, 'pollution': 7, 'issue': 7, 'snowstorms': 7,
             'denial': 7, 'vulnerability': 7, 'poverty': 7, 'already': 7, 'hit': 7, 'human': 7, 'clean': 7,
             'research': 7, 'affect': 7, 'seasonal': 7, 'exclusive': 7, 'cloud': 7, 'effect': 7, 'yet': 7, 'even': 7,
             'canadian': 7, 'contribute': 7, 'still': 7, 'coal': 7, 'mother': 7, 'decline': 7, 'solve': 7,
             'newsongreen': 7, 'food': 7, 'give': 7, 'photos': 7, 'tools': 7, 'experts': 7, 'cause': 7, 'eco': 7,
             'video': 7, 'work': 7, 'tedxvolcano': 7, 'brilliant': 7, 'claims': 7, 'eruptions': 7, 'agency': 6,
             'wine': 6, 'vs': 6, 'big': 6, 'storms': 6, 'doubters': 6, 'usa': 6, 'groups': 6, 'changing': 6, 'ash': 6,
             'ways': 6, 'says': 6, 'industrial': 6, 'key': 6, 'would': 6, 'ethiopia': 6, 'gop': 6, 'china': 6,
             'deadly': 6, 'releases': 6, 'fixing': 6, 'timecom': 6, 'something': 6, 'spill': 6, 'snowpocalypse': 6,
             'economic': 6, 'thought': 6, 'previously': 6, 'suggests': 6, 'preliminary': 6, 'support': 6, 'free': 6,
             'wolverine': 6, 'oceans': 6, 'whales': 6, 'event': 6, 'humanitarian': 6, 'bolivia': 6, 'failed': 6,
             'vatican': 6, 'disappearàthe': 6, 'uruguay': 6, 'right': 6, 'indigenous': 6, 'really': 6, 'call': 6,
             'rights': 6, 'nwf': 6, '100': 6, 'resorts': 6, 'ski': 6, 'european': 5, 'farmers': 5, 'motherjones': 5,
             'temps': 5, 'im': 5, 'wants': 5, 'back': 5, 'demand': 5, 'solar': 5, 'alaska': 5, 'days': 5, 'system': 5,
             'high': 5, 'extreme': 5, 'federal': 5, 'addressing': 5, '2': 5, 'giant': 5, 'w': 5, 'made': 5, 'bird': 5,
             'nasa': 5, 'say': 5, 'thats': 5, 'love': 5, '20': 5, 'antarctica': 5, 'april': 5, 'wwf': 5, 'grow': 5,
             'birds': 5, 'drought': 5, 'slow': 5, 'show': 5, 'ten': 5, 'interesting': 5, 'stake': 5, 'disprove': 5,
             'class': 5, 'hazardous': 5, 'httpisgdbit49': 5, 'first': 5, 'done': 5, 'ask': 5, 'tragedy': 5,
             'momentum': 5, 'gulf': 5, 'cycle': 5, 'tell': 5, 'trade': 5, 'renewable': 5, 'pika': 5, 'wont': 5,
             'last': 5, '30': 5, 'worlds': 5, 'apart': 5, 'theyll': 5, 'isnt': 5, 'point': 5, 'needs': 5, 'well': 5,
             'globalwarming': 5, 'poor': 5, 'baby': 5, 'increased': 5, 'yahoo': 5, 'un': 5, 'core': 5, 'local': 5,
             'ft': 5, 'international': 5, 'york': 5, 'larry': 5, 'bad': 5, 'using': 5, 'cricket': 4, 'india': 4,
             'cities': 4, 'oxfam': 4, 'summit': 4, 'means': 4, 'another': 4, 'evolution': 4, 'stretch': 4, 'valley': 4,
             'mountain': 4, 'sea': 4, 'accelerating': 4, 'higher': 4, 'less': 4, 'rare': 4, 'peanuts': 4, 'meat': 4,
             'recycling': 4, 'innovation': 4, 'called': 4, 'vancouver': 4, 'humaninduced': 4, 'primarily': 4,
             'unequivocal': 4, 'declares': 4, 'dept': 4, 'cochabamba': 4, 'doubt': 4, 'working': 4, 'two': 4,
             'refute': 4, 'said': 4, 'kill': 4, 'scientist': 4, 'small': 4, 'photo': 4, 'rice': 4, 'public': 4,
             'praise': 4, 'trigger': 4, 'industry': 4, 'resources': 4, 'shortened': 4, 'implicated': 4, 'released': 4,
             'worsen': 4, 'currents': 4, 'whale': 4, 'missing': 4, 'early': 4, 'links': 4, 'oxygen': 4, 'despite': 4,
             'government': 4, 'years': 4, 'sun': 4, 'denier': 4, 'warmingthe': 4, 'posted': 4, 'httpbitlycoowit': 4,
             'set': 4, 'ca': 4, 'clues': 4, 'ideas': 4, 'hey': 4, 'expert': 4, 'c': 4, 'billion': 4, 'gets': 4,
             'linked': 4, 'expected': 4, 'transforming': 4, 'caused': 4, 'much': 4, 'affecting': 4, 'temperatures': 4,
             'fall': 4, 'aware': 4, 'bigger': 4, 'tackling': 4, 'killing': 4, 'story': 4, 'data': 4, 'business': 4,
             'risks': 4, 'today': 4, 'acidity': 4, 'reveal': 4, 'avoidglobalwarmingcom': 4, 'fossil': 4, 'hard': 4,
             'debate': 4, 'sink': 4, 'homes': 4, 'prepare': 4, 'face': 4, 'single': 4, 'sure': 4, 'wednesday': 4,
             'large': 4, 'boomers': 4, 'tsunami': 4, 'agriculture': 4, 'meatwise': 4, 'law': 4, 'guide': 4, 'watch': 4,
             'alternative': 4, 'economics': 4, 'times': 4, 'parks': 4, '2025953368': 4, 'involved': 4,
             'sustainability': 4, 'thaw': 4, 'cap': 4, 'magazine': 4, 'goldberg': 4, 'jonah': 4, 'glacial': 4,
             'companies': 4, 'city': 4, 'lake': 4, 'administration': 3, 'scary': 3, 'californias': 3, 'lead': 3,
             'normal': 3, 'consider': 3, 'explore': 3, 'instead': 3, 'e': 3, 'politicians': 3, 'pastoralists': 3,
             'massive': 3, '3': 3, 'south': 3, 'production': 3, 'attacks': 3, 'gift': 3, '24': 3, 'chu': 3, 'steven': 3,
             'secretary': 3, 'earthquakes': 3, 'communities': 3, 'warned': 3, 'podcast': 3, 'preparing': 3,
             'population': 3, 'either': 3, 'senate': 3, 'nytimescom': 3, 'competing': 3, 'southern': 3, 'capitalism': 3,
             'lots': 3, 'efficiency': 3, 'peru': 3, 'earlywarning': 3, 'best': 3, 'become': 3, 'ecosystems': 3,
             'measurable': 3, 'fast': 3, 'find': 3, 'sec': 3, 'petition': 3, 'americans': 3, 'examining': 3,
             'actions': 3, 'mean': 3, 'sediments': 3, 'predicting': 3, 'line': 3, 'deny': 3, 'increasingly': 3,
             'clima': 3, 'noaa': 3, 'youtube': 3, 'ecoguilt': 3, 'ease': 3, 'buying': 3, 'clear': 3, 'bloga': 3,
             'offers': 3, 're': 3, 'newsbusters': 3, 'accountability': 3, 'blizzard': 3, 'unlikely': 3, 'emissions': 3,
             'greenhouse': 3, 'dr': 3, 'angeles': 3, 'los': 3, 'discussion': 3, 'technology': 3, 'led': 3, 'cement': 3,
             'weapon': 3, 'latest': 3, 'basic': 3, 'presented': 3, 'crisis': 3, 'spark': 3, 'volcanoesclimate': 3,
             'heated': 3, 'cooling': 3, 'newspaper': 3, 'b2p': 3, 'temperature': 3, 'mau': 3, 'himalayas': 3,
             'eastern': 3, 'wwfus': 3, 'extend': 3, 'cool': 3, 'black': 3, 'major': 3, '1': 3, 'perhaps': 3,
             'thousands': 3, 'battle': 3, 'technique': 3, 'discovery': 3, 'drug': 3, 'travel': 3, 'ecointeractive': 3,
             'larger': 3, '22': 3, 'doesnt': 3, 'storm': 3, 'coastal': 3, 'listen': 3, 'development': 3, 'decades': 3,
             'patterns': 3, 'comes': 3, 'soon': 3, 'combating': 3, 'little': 3, 'someone': 3, 'account': 3,
             'florida': 3, 'trouble': 3, 'highs': 3, 'nearrecord': 3, 'organicnewyork': 3, '1213hr': 3, 'youre': 3,
             'media': 3, 'proposed': 3, 'countries': 3, 'developed': 3, 'leads': 3, 'mountains': 3, 'wanted': 3,
             'reading': 3, 'view': 3, 'disproves': 3, 'symptoms': 3, 'patient': 3, 'james': 3, 'services': 3,
             'continent': 3, 'society': 3, '4': 3, 'california': 3, 'httpbitlyb8ajbg': 3, 'mark': 3, 'charles': 3,
             'organic': 3, 'bio': 3, 'abc': 3, 'many': 3, 'ryannewyork': 3, 'adapt': 3, 'weekend': 3,
             'jaymiheimbuch': 3, 'sejorg': 3, 'bradplumer': 3, 'strong': 3, 'frontline': 3, 'million': 3, 'canada': 3,
             'icelands': 3, 'sciencedaily': 3, 'bassey': 3, 'nnimmo': 3, 'environmentalist': 3, 'nigerian': 3,
             'struggle': 3, 'senators': 3, 'events': 3, 'fellow': 3, 'fuels': 3, 'present': 3, 'shop': 3, 'policy': 3,
             'meeting': 3, 'co2': 3, 'tree': 3, 'traditional': 3, 'relocation': 3, 'indians': 3, 'kuna': 3, 'know': 3,
             'believe': 3, 'enviro': 3, 'ndp': 3, 'vote': 3, 'talks': 3, 'peace': 3, 'monitoring': 3, 'east': 3,
             'animal': 3, 'place': 3, 'article': 3, 'comprehensive': 3, 'plant': 3, 'congress': 3, 'risk': 3,
             'acidification': 3, 'wired': 3, 'disease': 3, 'curable': 3, 'treating': 3, 'icelandic': 3, 'activity': 3,
             'got': 3, 'indigenousissue': 3, 'plan': 3, 'age': 3, 'tednews': 3, 'talking': 3, 'oil': 3, '5': 3,
             'february': 3, 'httpbitlyamgm77': 3, 'thanksgiving': 3, 'ap': 3, 'warmingsalt': 3, 'wpccc': 2,
             'bravenewclimate': 2, 'american': 2, 'use': 2, 'counterparts': 2, 'keen': 2, 'ceos': 2, 'group': 2,
             'httpbitlyaybo8z': 2, 'announced': 2, 'wow': 2, 'huffpostgreen': 2, 'states': 2, 'united': 2,
             'pressuring': 2, 'faced': 2, 'gravest': 2, 'address': 2, 'failing': 2, 'leaders': 2, 'warminggreen': 2,
             'orderfight': 2, 'house': 2, 'ur': 2, 'biz': 2, 'bransons': 2, 'richard': 2, 'dark': 2, 'cursing': 2,
             'movement': 2, 'empowering': 2, 'ethiopian': 2, 'claiming': 2, 'thriving': 2, 'tropical': 2, 'violent': 2,
             'httpbitlydxiafb': 2, 'trillion': 2, 'assessment': 2, 'sequestration': 2, 'always': 2, 'geopolitics': 2,
             'brain': 2, 'short': 2, 'httpbitlyrfdecline': 2, 'reversing': 2, 'rtr': 2, 'calcuttatube': 2, 'gecko': 2,
             'revolution': 2, 'start': 2, 'games': 2, 'snowless': 2, 'acknowledge': 2, 'drudge': 2, 'ericboehlert': 2,
             'stopglobalwarming': 2, 'river': 2, 'seasons': 2, 'altering': 2, 'climateproject': 2, 'earlier': 2,
             'align': 2, 'unio': 2, 'following': 2, 'bizarre': 2, 'facing': 2, 'london': 2, 'history': 2, 'bats': 2,
             'disaster': 2, 'maine': 2, 'benefits': 2, 'toward': 2, 'slide': 2, 'white': 2, 'beauty': 2,
             'httplatmsccps7q': 2, 'control': 2, 'filmmaker': 2, 'living': 2, 'httpbitlyb27x1s': 2, 'poisoning': 2,
             'sues': 2, 'completely': 2, 'asian': 2, 'reinvent': 2, 'endangering': 2, 'snowmageddon': 2, 'space': 2,
             'pic': 2, 'known': 2, 'pentagon': 2, 'generals': 2, 'families': 2, 'sense': 2, 'glossy': 2, 'gl': 2,
             'cleantech': 2, 'cant': 2, 'reducing': 2, 'tied': 2, 'bye': 2, 'conscious': 2, 'wish': 2, 'doc': 2,
             'away': 2, 'melting': 2, 'crop': 2, 'met': 2, 'slowly': 2, 'enough': 2, 'cannot': 2, 'dare': 2, 'man': 2,
             'ne': 2, 'reliable': 2, 'outoftouch': 2, 'kesner': 2, 'letterwriter': 2, 'recent': 2, 'facts': 2,
             'chinaenergy': 2, 'also': 2, 'long': 2, 'energyclimate': 2, 'switch': 2, 'coping': 2, 'sciam': 2, 'wed': 2,
             'finds': 2, 'hate': 2, 'e2wire': 2, 'canadas': 2, 'agenda': 2, 'end': 2, 'palin': 2, '2c': 2, 'armenia': 2,
             'httpowly178ewd': 2, 'teens': 2, 'onestop': 2, 'youth': 2, 'inconvenient': 2, 'role': 2, 'zealand': 2,
             'delhi': 2, 'officials': 2, 'httpbitlybqan2x': 2, 'building': 2, 'southe': 2, 'bring': 2, 'limpopo': 2,
             'tea': 2, 'grist': 2, 'pushing': 2, 'protocols': 2, 'barrett': 2, 'listings': 2, 'confronting': 2,
             'yorkers': 2, 'pbs': 2, 'socent': 2, '7': 2, 'cure': 2, 'idea': 2, 'explosive': 2, 'hoax': 2, 'problem': 2,
             'alpha': 2, 'httpbitlycy7jc8': 2, 'wiretapmagazine': 2, 'diggsciences': 2, 'efforts': 2, 'lauded': 2,
             'automotive': 2, 'coda': 2, 'come': 2, 'sheets': 2, 'signs': 2, 'troubling': 2, 'drill': 2,
             'geologists': 2, 'pls': 2, 'trend': 2, 'record': 2, 'warmest': 2, 'doubting': 2, 'cut': 2, 'estimate': 2,
             'writes': 2, 'pickens': 2, 'warminghugh': 2, 'tackles': 2, 'tips': 2, '50': 2, 'wwfclimate': 2, 'cbs': 2,
             'ama': 2, 'stats': 2, 'httpbitlycll6li': 2, 'lol': 2, 'danger': 2, 'join': 2, 'httpgooglz8ka': 2,
             'milieunet': 2, 'boliviaun': 2, '2009': 2, 'count': 2, 'pollen': 2, 'ha': 2, 'awaiting': 2, 'bomb': 2,
             'predicted': 2, 'pics': 2, 'jerryjamesstone': 2, 'step': 2, 'challenge': 2, 'solution': 2, 'motorola': 2,
             'member': 2, 'ccx': 2, 'australia': 2, 'httpbitlydfi3es': 2, 'animals': 2, 'studied': 2, 'light': 2,
             'logbooks': 2, 'keepers': 2, 'actually': 2, 'leading': 2, 'gore': 2, 'al': 2, 'hurting': 2, 'might': 2,
             'service': 2, 'fish': 2, 'protection': 2, 'donàt': 2, 'bbc': 2, 'negatively': 2, 'tr': 2, 'bringing': 2,
             'b': 2, 'esty': 2, 'daniel': 2, 'given': 2, 'old': 2, 'power': 2, 'steps': 2, 'leadership': 2, 'pew': 2,
             'perfect': 2, 'jobs': 2, 'series': 2, 'highlight': 2, 'closer': 2, 'contributes': 2, 'drilling': 2,
             'invasion': 2, 'squid': 2, 'fault': 2, 'nothing': 2, 'student': 2, 'gotten': 2, 'price': 2, 'absorbing': 2,
             'soil': 2, 'qualified': 2, 'giving': 2, 'curve': 2, 'throw': 2, 'teams': 2, 'baseball': 2, 'league': 2,
             'gathering': 2, 'httpbitlybtyohc': 2, 'httpbitlybzv5is': 2, 'idiotic': 2, 'yup': 2, 'noreen1': 2,
             'mention': 2, 'implications': 2, 'dead': 2, 'thinks': 2, 'everyone': 2, 'advise': 2, 'gemswinc': 2,
             'among': 2, 'province': 2, 'thoreaus': 2, 'ol': 2, 'httpbitlycdr9xj': 2, 'theres': 2, 'cold': 2, 'week': 2,
             'crock': 2, 'amazon': 2, 'treehugger': 2, 'ago': 2, 'counc': 2, 'defense': 2, 'millions': 2, 'heart': 2,
             'alexia': 2, 'codex': 2, 'education': 2, 'enable': 2, 'grant': 2, 'discovered': 2, 'warmingresearchers': 2,
             'economists': 2, 'heard': 2, 'disrupting': 2, 'problems': 2, 'disclosing': 2, 'asia': 2, 'se': 2,
             'started': 2, 'climategate': 2, 'milesgrant': 2, 'faces': 2, 'county': 2, 'ventura': 2, 'dwindles': 2,
             'blamed': 2, 'driver': 2, 'catastrophic': 2, 'reasons': 2, 'changed': 2, 'bc': 2, 'ratigan': 2,
             'teaparty': 2, 'overwhelming': 2, 'blooms': 2, 'biologist': 2, 'uw': 2, 'quixotecenter': 2, 'lessons': 2,
             'depletionreduce': 2, 'organisms': 2, 'populations': 2, 'floor': 2, 'calling': 2, 'myth': 2, 'fb': 2,
             'reset': 2, 'password': 2, 'forgot': 2, 'siliconindia': 2, 'warmingdont': 2, 'effectively': 2,
             'landmark': 2, 'defends': 2, 'official': 2, 'top': 2, 'graham': 2, 'kerry': 2, 'deal': 2, 'claim': 2,
             'go': 2, 'realdocwatson': 2, 'oh': 2, 'greenpeac': 2, 'gases': 2, 'battling': 2, 'teaching': 2, 'wrong': 2,
             'httpisgd5fsmv': 2, 'stories': 2, 'witness': 2, 'material': 2, 'looking': 2, 'number': 2,
             'httpbitly9m2qfp': 2, 'deaths': 2, 'strange': 2, 'contributing': 2, 'suspect': 2, 'burning': 2, 'syrup': 2,
             'maple': 2, 'hiding': 2, 'military': 2, 'move': 2, 'scaledback': 2, 'australias': 2, 'proves': 2,
             'msnbcs': 2, 'rates': 2, 'complicate': 2, 'topography': 2, 'eruption': 2, 'vast': 2, 'warminga': 2,
             'modern': 2, 'httpbitlybdlpvw': 2, 'assess': 2, 'volunteers': 2, 'budburst': 2, 'accelerated': 2,
             'waves': 2, 'evrythings': 2, 'mental': 2, 'inclde': 2, 'u': 2, 'affctd': 2, 'diseases': 2, '11': 2,
             'identifies': 2, 'sighs': 2, 'environmentalism': 2, 'loved': 2, 'kinds': 2, 'came': 2, 'lilferret': 2,
             'discuss': 2, 'hansen': 2, 'joins': 2, 'rogers': 2, 'heather': 2, 'tonight': 2, 'httpbitlyafrapn': 2,
             'us2972': 2, 'chan': 2, 'exceptional': 2, 'periods': 2, 'geosphere': 2, 'stunner': 2, 'royal': 2,
             'httpnytimsdocid8': 2, 'changegood': 2, 'afford': 2, 'mpondfieldhow': 2, 'noreenahertz': 2, 'scott': 2,
             'michael': 2, 'govt': 2, 'blogger': 2, 'huffington': 2, 'huffpo': 2, 'warnings': 2, 'httpbitlyces5qn': 2,
             'reform': 2, 'immigration': 2, 'preview': 2, 'sneak': 2, 'stranded': 2, 'mertes': 2, 'cara': 2, '9': 2,
             'effective': 2, 'remain': 2, 'tells': 2, 'consequences': 2, 'social': 2, 'result': 2, 'wa': 2, 'main': 2,
             'oslo': 2, 'partner': 2, 'germany': 2, 'democracynow': 2, 'changes': 2, 'salinity': 2, '16': 2,
             'pulling': 2, 'advances': 2, 'costs': 2, 'financial': 2, 'hope': 2, 'saw': 2, 'conf': 2, 'gather': 2,
             'western': 2, 'stakeholders': 2, 'csr': 2, 'calls': 2, 'httpbitly9yhs1c': 2, 'httpbitly9btud0': 2,
             'everythin': 2, 'genius': 2, 'create': 2, 'compromise': 2, 'theory': 2, 'heavy': 2, 'please': 2,
             'threats': 2, 'dhs': 2, 'challenges': 2, 'types': 2, 'socmedia': 2, 'olympics': 2, 'pass': 2, 'mps': 2,
             'liberal': 2, 'mignatieff': 2, 'mobilize': 2, 'art': 2, 'tipping': 2, 'special': 2, 'mediaglobal': 2,
             'drudgereport': 2, 'near': 2, 'humanitynews': 2, 'voice': 2, 'enjoyed': 2, 'anonymous': 2, 'focus': 2,
             'climatenews': 2, 'monday': 2, 'bateman': 2, 'cynthia': 2, 'keep': 2, 'krugman': 2, 'political': 2,
             'vid': 2, 'triggers': 2, 'icons': 2, 'continues': 2, '1213hrget': 2, 'wiredcom': 2, 'greenforyou': 2,
             'attack': 2, 'though': 2, 'vol': 2, 'diary': 2, 'earthweek': 2, 'volcanos': 2, 'unplug': 2, 'calif': 2,
             'took': 2, 'climateprogress': 2, 'unwillingness': 1, 'pretending': 1, 'bcbg25': 1,
             'httpwwwoneclimatenetbolivia': 1, '1922': 1, 'cmpcc': 1, 'counting': 1, 'httpowly16vsyu': 1,
             'httpbitlya1yawl': 1, 'httpowly16xwc8': 1, 'ammo': 1, 'flakes': 1, 'httpoohjacomxbm8b': 1,
             'httpurl4eu2abii': 1, 'redistribution': 1, 'chews': 1, 'httpisgd7yox4': 1, 'wunderground': 1, 'masters': 1,
             'jeff': 1, 'txvoodoo': 1, 'biodiversitylink': 1, 'changelink': 1, 'httpbitlyabdh6c': 1, 'wrath': 1,
             'carbondiplomacy': 1, 'httpbitly9fkhqu': 1, 'paris': 1, 'afp': 1, 'httpsocwrkorg8696': 1, 'sustainable': 1,
             'socialistviews': 1, 'kalimakhus': 1, 'httpwwwnwforg': 1, 'homepage': 1, 'oddball': 1, 'margaretkinney': 1,
             'httpbitlyaym1uc': 1, 'embrace': 1, 'failure': 1, 'africas': 1, 'bloomberg': 1, 'source': 1, 'offset': 1,
             'innovate': 1, 'urged': 1, 'african': 1, 'httpbizwirepr70qe2': 1, 'biotechnology': 1, '2010': 1,
             'httpbitlyajhkwp': 1, '350': 1, 'countriesblocks': 1, 'morning': 1, 'mapping': 1, 'team': 1,
             'httpbitlyaeoudt': 1, 'serve': 1, 'per': 1, 'barrels': 1, 'uses': 1, 'america': 1, 'dilemma': 1, 'fuel': 1,
             'myedulinks': 1, 'httpretwtme1lvj9': 1, 'abroad': 1, 'carbonbased': 1, 'theclimatedesk': 1, 'seriously': 1,
             'leap': 1, 'frogs': 1, 'httpbitlyclb8vf': 1, 'httpdlvrit1fh1': 1, 'httpbitlyavthbz': 1, 'award': 1,
             'wins': 1, 'documentary': 1, 'gandhis': 1, 'rohit': 1, 'sharethis': 1, 'httpsharesalckr': 1, 'rises': 1,
             'httpowly1bphq': 1, 'occurring': 1, 'thator': 1, 'roughhas': 1, 'yikessounds': 1, 'tasha9698': 1,
             'httpretwtme1msqx': 1, 'coordinated': 1, 'prospects': 1, '873': 1, 'example': 1, 'httpbitlyam0dlj': 1,
             'rttreehugger': 1, 'httpbitly9pil1g': 1, 'results': 1, 'surprising': 1, 'httpbitlyabvrib': 1,
             'congressman': 1, 'dem': 1, 'httppingfmgjlkg': 1, 'httpbitlybonsiq': 1, 'west': 1, 'httpbitlyc8unbr': 1,
             'land': 1, 'httpbitly9lomhn': 1, 'wouldve': 1, 'indigpplsrsrcs': 1, 'httptinyurlcomyjxebsw': 1,
             'httptinyurlcom2cck5xd': 1, 'awareness': 1, 'car': 1, 'overview': 1, 'httpbitlybncm5p': 1, 'running': 1,
             'la': 1, 'alarmism': 1, 'httpowly1ogzuk': 1, 'httpbitlybiac01': 1, 'covering': 1, 'updates': 1, 'daily': 1,
             'briefing': 1, 'commodities': 1, 'opalesque': 1, 'nwifc': 1, 'httpretwtme1myw7': 1, 'salish': 1,
             'responding': 1, 'native': 1, 'httpoohjacomxbk49': 1, 'httpbitlydcwxcg': 1, 'pelosi': 1, 'commercial': 1,
             'gingrich': 1, 'httpbitlyahg2tk': 1, 'violation': 1, 'medicine': 1, 'fundamental': 1,
             'httphuffingtonpostcom20100421springcomes10daysearln545790html': 1, 'httpbitlyb8ifs9': 1,
             'changehttpbitlybgxoba': 1, 'warms': 1, 'release': 1, 'soils': 1, 'slate': 1, 'httpawesm55qvf': 1,
             'httpoohjacomxbopk': 1, 'observatory': 1, 'dynamics': 1, 'nasas': 1, 'worthless': 1, 'maybe': 1,
             'httpbitlyali6md': 1, 'debunks': 1, 'benbalter': 1, 'httpblogalgorecom201002milibandfightsbackhtml': 1,
             'httpbitly95qwi1': 1, 'noisemachine': 1, 'httpbitly9nkecc': 1, 'conservative': 1, 'freeze': 1, 'mmfa': 1,
             'httptinyurlcomy8fzja2': 1, 'l': 1, 'person': 1, 'spokes': 1, 'whose': 1, 'httpbitlybnzfzj': 1,
             'profiling': 1, 'psychological': 1, 'cledzrosario': 1, 'necessarily': 1, 'stfu': 1, 'perceptions': 1,
             'pastoralist': 1, 'tests': 1, 'kenya': 1, 'httpbitlyb8mqcu': 1, 'peril': 1, 'alps': 1, 'sierras': 1,
             'repoweramerica': 1, 'httpbitlybxmwb8': 1, 'cejapa': 1, 'httpisgd85qr9': 1, 'editorial': 1,
             'washingtonpost': 1, 'greentech': 1, 'httpjmp9bcwf7': 1, 'http': 1, 'ecopirate': 1, 'therightblue': 1,
             'saving': 1, '34': 1, 'oceanleadership': 1, 'httpretwtme1n01z': 1, 'storming': 1, 'httpbitlybpx3xh': 1,
             'httpowly13wxw': 1, 'minigrants': 1, 'awards': 1, 'httpbitlyd8sx0d': 1, 'timecomhttpbitlycwrrmi': 1,
             'httpbitlyd9iyjy': 1, 'httpbitly9mhr4g': 1, 'sourc': 1, 'evolutionary': 1, 'fashion': 1, 'journeys': 1,
             'longdistance': 1, 'httpbitly9bdfvr': 1, 'httpbitly9cqrqj': 1, 'letter': 1, 'markets': 1, 'cquestor': 1,
             'httpbitly9trngu': 1, 'httpowly16xgtm': 1, 'blames': 1, 'httpbitly8zpofc': 1, 'energycollectiv': 1,
             'requires': 1, 'recession': 1, 'retech': 1, 'pena': 1, 'politics': 1, 'httpbitlyc6l90x': 1,
             'proponents': 1, 'somethings': 1, 'weatherchicago': 1, 'supposedly': 1, 'damn': 1, 'alexpriest': 1,
             'woot': 1, 'httpbitlycpfnbl': 1,
             'httpnewyorkcityandpresscom20100415climatechangecouldraisecostallergies': 1, 'httpbitlyaykzju': 1,
             'worl': 1, 'seeks': 1, 'lifeline': 1, 'httpbitlyb2rj5v': 1, 'used': 1, 'httptinyurlcomyf2np2u': 1,
             'deforestation': 1, 'multiple': 1, 'califor': 1, 'cahill': 1, 'kimberley': 1, 'buzz': 1,
             'httpbitlyccurkq': 1, 'survivability': 1, 'passive': 1, 'framed': 1, 'partyers': 1, 'scaredycat': 1,
             'httpurl4eu2r22o': 1, 'ifrsadvantage': 1, 'httpretwtme1lscq': 1, 'accountancy': 1, 'profession': 1,
             'greens': 1, 'httptumblrcomx5x8kszx2': 1, 'stevegeritano': 1, 'httpretwtme1mnc2': 1, 'httphufftod0ejgu': 1,
             'shortage': 1, 'biochar': 1, 'g20': 1, 'g8': 1, 'carbonmarket': 1, 'httpretwtme1mqzf': 1,
             'guardiancouk': 1, 'chief': 1, 'google': 1, 'httpwwwpaltalknewsnetworkcomnode2210': 1, 'mmaction': 1,
             'httptinyurlcom3y6j4cj': 1, 'council': 1, 'rapidly': 1, 'httpowly1774ms': 1, 'httpbitly8xlipp': 1,
             'httpnxyink9oox': 1, 'httpbitlyduiycm': 1, 'candle': 1, 'gershon': 1, 'david': 1,
             'httptinyurlcom3a67ary': 1, 'rural': 1, 'devastating': 1, 'gopfail': 1, 'dick': 1, 'strapon': 1, '12': 1,
             'gf': 1, 'ing': 1, 'httpoohjacomx6g2p': 1, 'warmingwashington': 1, 'proposes': 1, 'ecoactions': 1,
             'greenistweet': 1, 'httpretwtme1mrgp': 1, 'httpnytims90pdbb': 1, 'determined': 1, 'imperiled': 1,
             'httpbitlydmimzf': 1, 'sentinel': 1, 'period': 1, 'areas': 1, 'non': 1, 'otherwise': 1, 'appear': 1,
             'bacteria': 1, 'illnesses': 1, 'httpbitly9dusaa': 1, 'mandate': 1, 'httpbitlybrzk8j': 1, 'hits': 1,
             'delta': 1, 'raysfreedomhash': 1, 'httpowly1odxhp': 1, 'httpbitlybvg95c': 1, 'httpbitlyc9rnr6': 1,
             'httpowly16uupb': 1, 'update': 1, 'ignorance': 1, 'httpbitly7ndfrn': 1, 'originally': 1, 'hurtful': 1,
             'worldwide': 1, 'messing': 1, 'totally': 1, 'blognewsweb': 1, 'httpretwtme1ms5u': 1, 'n': 1,
             'innovatively': 1, 'mulch': 1, 'weekly': 1, 'mayoroflondon': 1, 'httpretwtme1lwvs': 1, 'londoners': 1,
             'mayor': 1, 'httpbitlyawfkhw': 1, 'httpbitlyajksz3': 1, 'kaskadia': 1, 'httpretwtme1lytc': 1,
             'environmentalresearchweb': 1, 'httptinyurlcom2vwys8q': 1, 'scienti': 1, 'creaney': 1, 'ruairi': 1,
             'macleod': 1, 'fiona': 1, 'month': 1, 'crippling': 1, 'push': 1, 'gurianpeck': 1, 'suffer': 1,
             'england': 1, 'httpbitlyalyhq4': 1, 'acosta': 1, 'ins': 1, 'ips': 1, 'sites': 1, 'net': 1,
             'httpoohjacomxbpyl': 1, 'circuits': 1, 'gw': 1, 'sake': 1, 'repubs': 1, 'replace': 1, 'saying': 1,
             'guess': 1, 'httpbitlyconbco': 1, 'httpbitlyb3dgcw': 1, 'kids': 1, 'standards': 1, 'ozone': 1,
             'httpbitly9ab5sb': 1, 'harm': 1, 'sources': 1, 'dealt': 1, 'httpretwtme1lvky': 1, 'saran': 1, 'shyam': 1,
             'democracy': 1, 'mobilising': 1, 'college': 1, 'schumacher': 1, '10cities': 1, 'uk': 1,
             'httpbitlyavp2gd': 1, 'accelerate': 1, 'httpbitlybb2l7d': 1, 'occurred': 1, 'display': 1, 'confirms': 1,
             'http5vj09tk': 1, 'credits': 1, 'daunting': 1, 'seems': 1, 'greener': 1, 'httpgoogl5ul1': 1,
             'httpbitlybkv0kp': 1, 'instant': 1, 'try': 1, 'sincerely': 1, 'httpretwtme1mssh': 1,
             'httpdiggcomd31puxtt': 1, 'exciting': 1, 'apocalypsenow': 1, 'outcomes': 1, 'predict': 1, 'sometimes': 1,
             'httpbitlybw322k': 1, 'httpoohjacomxbhvz': 1, 'httplatmsdy3ifl': 1, 'eyjafjallajo': 1, 'questions': 1,
             'answer': 1, 'icecovered': 1, 'terrible': 1, 'rainstorms': 1, 'httpviigoim3fsu': 1,
             'httptinyurlcomyzq4olr': 1, 'kick': 1, 'hand': 1, 'httpbitlydausja': 1, 'thinking': 1, 'lately': 1,
             'papers': 1, 'mocked': 1, 'jindal': 1, 'bobby': 1, 'shoq': 1, 'iandavidb': 1, 'beckbasher': 1,
             'httpbitlyb5cajw': 1, 'tourism': 1, 'side': 1, 'supply': 1, 'httpowly15s0o': 1, 'httpbitlyavw0at': 1,
             'httpowly1xagk': 1, 'blastoffgt': 1, 'satellite': 1, 'launches': 1, 'httpbitlyaz754n': 1, 'nail': 1,
             'tooth': 1, 'chunks': 1, 'seeing': 1, 'cdnpoli': 1, 'targets': 1, 'stage': 1, 'passes': 1, 'hurrah': 1,
             'httpowly178p5k': 1, 'tribeca': 1, 'premiere': 1, 'copeland': 1, 'sebastian': 1, 'jessicaalba': 1,
             'jpatricof': 1, 'tribecafilmfest': 1, 'httpbitlycx7jz2': 1, 'tha': 1, 'topnews': 1, 'loss': 1,
             'httpbitlybocsqs': 1, 'alertnetclimate': 1, 'httpretwtme1ly7u': 1, 'disasterun': 1, 'recipe': 1,
             'alertnet': 1, 'httpbitly8zcerl': 1, 'httpbitlybemhl3': 1, 'httpbitlyalhpwn': 1, 'httpbitlybjsszy': 1,
             'httpbitlyao6kn0': 1, 'httpbitlydzykhk': 1, 'httpffimfbj8k': 1, 'httpbitlycuf4kq': 1, 'producing': 1,
             'jacobs': 1, 'max': 1, 'unemploymentchoose': 1, 'httpbitly9rps9p': 1, 'nationa': 1, 'according': 1,
             'httpbitlya5qlf0': 1, 'suspend': 1, 'initiative': 1, 'ballot': 1, 'backers': 1, 'revenge': 1, 'browns': 1,
             'jerry': 1, 'httphufftoa3ocsr': 1, 'distributed': 1, '31': 1, 'wor': 1, 'taking': 1, 'httpbitlydb2a9l': 1,
             'httpbitlyaffkez': 1, 'crime': 1, 'guilty': 1, 'youd': 1, 'left': 1, 'tolerant': 1, 'gbjoe': 1,
             'httpwwwnrdcactionfundorgthisisourmomentp1281c349598s762984l81599': 1, 'httpbitlybgm3w5': 1, 'globe': 1,
             'travels': 1, 'httpbitlycpfcze': 1, 'httpbitlyasmjgu': 1, 'genocide': 1, 'glauricella': 1,
             'httpbitlybrjnry': 1, 'liability': 1, 'rules': 1, 'disclosure': 1, 'corporate': 1, 'complementary': 1,
             'httpbitlybk55t0': 1, 'guardianscience': 1, 'gclugo': 1, 'httpbitlyckrjpw': 1, 'accel': 1,
             'httpbitly9ufzaj': 1, 'frozen': 1, 'radar': 1, 'navy': 1, 'navynews': 1, 'blogdiva': 1, 'ab': 1,
             'httpbitlydrw0nu': 1, 'marine': 1, 'dioxide': 1, 'atmospheric': 1, 'httpbitlyak8oag': 1, 'blindness': 1,
             'willful': 1, 'theologians': 1, 'warmingweirding': 1,
             'httplosangelescityandpresscomnews20100501religiousspinclimatechange': 1, 'spin': 1, 'religious': 1,
             'httpbitlyce3hox': 1, 'h': 1, 'secluded': 1, 'eight': 1, 'ministers': 1, 'foreign': 1,
             'rubberstamprosk': 1, 'sequels': 1, 'xmen': 1, 'lack': 1, 'lt': 1, 'httpisgd7gspu': 1, 'declines': 1,
             'huffingtonpostz': 1, 'rockthevote': 1, 'signed': 1, 'narrative': 1, 'consensus': 1, 'bluffing': 1,
             'governamerica': 1, 'httpbitlyddmoy0': 1, 'piles': 1, 'described': 1, 'aid': 1, 'mongolia': 1,
             'livestock': 1, 'gayandright': 1, 'httpowly14obf': 1, 'idiots': 1, 'grasp': 1, 'disturbedwater': 1,
             'httptinyurlcomyaqbeop': 1, 'httpfwixcomarticle319cd7519b2': 1, 'httpbitlybecmid': 1, 'denyers': 1,
             'upcoming': 1, 'shooting': 1, 'httpwwwenvironmentportalinnode302789': 1, 'gilaaa': 1, 'panas': 1,
             'chialiciouss': 1, 'olipvia': 1, 'httpbitly9qoabv': 1, 'httpurl4eu353hm': 1, 'numbers': 1,
             'overpopulation': 1, 'dissecting': 1, 'httpretwtme1lykq': 1, 'snowtorious': 1, 'bizzards': 1,
             'httpmigremefu6k': 1, 'things': 1, 'globalalert': 1, 'counts': 1, 'offthecharts': 1, 'culprit': 1,
             'httptweetphotocom10483335': 1, 'positive': 1, 'httpbitlyccqa1y': 1, 'austral': 1, 'conducted': 1,
             'indyposted': 1, 'weird': 1, 'httpbitlyat4b32': 1, 'islands': 1, 'httptwitpiccom115sjc': 1, 'maldives': 1,
             'beautiful': 1, 'posts': 1, 'astronaught': 1, 'httpbitly9a8mij': 1, 'httpbitlyd1szfe': 1, 'slideshow': 1,
             'panteraonca07': 1, 'httpbitlyby5fpn': 1, '2ác': 1, 'copenhagen': 1, 'proposals': 1, 'reduction': 1,
             'au': 1, 'uninfo': 1, 'undpi': 1, 'sivacolundhu': 1, 'renata': 1, 'gender': 1, 'wedoworldwide': 1,
             'harris': 1, 'rachel': 1, 'httpoohjacomx6ouc': 1, 'pikaclimate': 1, 'tiny': 1, 'protections': 1,
             'denies': 1, 'luck': 1, 'httpbitlydmnjxj': 1, 'httpbitlyasute0': 1, 'sad': 1, 'nutting': 1,
             'deniability': 1, 'plausible': 1, 'scale': 1, 'wilshipley': 1, 'httpbitlycldu6w': 1, 'acs': 1,
             'enlisting': 1, 'httpbitly9xcq7d': 1, 'sniffly': 1, 'nwfs': 1, 'httpretwtme1luqs': 1, '350ppm': 1,
             'httpbitlycoz3qj': 1, 'oz': 1, 'australian': 1, 'httpbitly9o8f9y': 1, 'httpbitlycpdg4r': 1, 'kcrws': 1,
             'httpbitlyd7ycku': 1, 'httpbitlybivncv': 1, 'dummies': 1, 'chalk': 1, 'unbelievable': 1, 'august': 1,
             'nyc': 1, 'climbing': 1, '83á': 1, 'ad': 1, 'businesses': 1, '3k': 1, 'consciousness': 1, 'shift': 1,
             'httptinyurlcomy3z9q2k': 1, 'httpbitlyd2xbro': 1, 'independence': 1, 'declaration': 1, 'signing': 1,
             'celebrate': 1, 'httpbitlyb4pcjd': 1, 'httptinyurlcomyystbl4': 1, 'smallscale': 1, 'reelection': 1,
             'probs': 1, 'immediate': 1, 'solved': 1, 'never': 1, 'macroprobs': 1, 'httpgooglfbzogme': 1,
             'httpbitlycl0a5p': 1, 'claireforman': 1, 'rate': 1, 'unprecedented': 1, 'chemistry': 1, 'atmospher': 1,
             'upper': 1, 'sediment': 1, 'reporting': 1, 'gregmitch': 1, 'httpbitlyckx6rh': 1, 'httpbitlycgqgiv': 1,
             'resp': 1, 'httpbitly9e5vfk': 1, 'httpbitly97dpxg': 1, 'kozloff': 1, 'nikolas': 1, 'interview': 1,
             'planetà': 1, 'entire': 1, 'affects': 1, 'americaàs': 1, 'àno': 1, 'lessens': 1, 'suns': 1, 'blocks': 1,
             'httptinyurlcomyjuj5a5': 1, 'my6sense': 1, 'wealth': 1, 'httpoohjacomxbvfc': 1, 'heartearth': 1,
             'approach': 1, 'httpwwwmnncomearthmattersclimatechangestoriesharshwintercausedbyclimatechange': 1,
             'harsh': 1, 'pants': 1, 'httpbitlybr4xlv': 1, 'cite': 1, 'elected': 1, 'country': 1, 'embarrassed': 1,
             'otoolefan': 1, 'httpxrlusbhg8dv': 1, 'httpbitlybia0k6': 1, 'las': 1, 'later': 1, 'asilomar': 1,
             'bioethicists': 1, 'httpowly1angq': 1, 'war': 1, 'winning': 1, 'httphufftod2rup1': 1, 'catholicsmg10': 1,
             'katrina': 1, 'hurricane': 1, 'dying': 1, 'httpbitly93juyj': 1, 'die': 1, 'ireversable': 1, 'sendboyle': 1,
             'httpbitlycw9vro': 1, 'httpbitlybglz82': 1, 'half': 1, 'roughly': 1, 'observational': 1, 'current': 1,
             'nsf': 1, 'httpbitlyakb76i': 1, 'httpcligsbzm9y': 1, 'prove': 1, 'test': 1, 'scientific': 1, 'profit': 1,
             'confusing': 1, 'economist': 1, 'classic': 1, 'httpbitly7fpptc': 1, 'sciencerss': 1, 'httpretwtme1mz7u': 1,
             'httpowly16xana': 1, 'tsunamis': 1, 'creator': 1, 'monologues': 1, 'vagina': 1, 'httpisgdbywgy': 1,
             'head': 1, 'guardian': 1, 'httpbitlycywgtn': 1, 'documents': 1, 'httpoohjacomxbmcr': 1, 'natparksnews': 1,
             'httpretwtme1mnul': 1, 'snowverkill': 1, 'httpbitly9ehobe': 1, 'httpjmpaonx07': 1,
             'httpwwwcsmonitorcomcarbonoffsets': 1, 'httpjmpnecir': 1, 'httpbitlydbqhig': 1, 'roadblock': 1,
             'wheres': 1, 'httpbitlybrhmyi': 1, 'dispersal': 1, 'influence': 1, 'variability': 1, 'changeclimate': 1,
             'understanding': 1, 'httpowly17bqit': 1, 'semibelievable': 1, 'httpbitlyagvnoh': 1, 'sync': 1, 'qdr': 1,
             'op': 1, 'operationfree': 1, 'epsclimate': 1, 'httphufftobhwmmz': 1, 'polluted': 1, 'worthwhile': 1,
             'definitely': 1, 'httpnytimscybfoi': 1, 'krugmans': 1, 'finally': 1, 'http4sqcom4qg5ch': 1, 'costco': 1,
             'fishmark': 1, 'httpbitlyc2y2r6': 1, 'gently': 1, 'losses': 1, 'httpbitlyaflska': 1, 'priority': 1,
             'hispanics': 1, '66': 1, 'httpbitlycs1aju': 1, 'ear': 1, 'flowering': 1, 'wisconsin': 1, 'central': 1,
             'researcher': 1, 'httpbitlybmfu80': 1, 'thatsright': 1, 'fan': 1, 'httpretwtme1lwkh': 1, 'hills': 1,
             'axelrod': 1, 'httpbitlycwrgor': 1, 'alerts': 1, 'red': 1, 'agencies': 1, 'httppbump83d': 1, 'joke': 1,
             'decrease': 1, 'en': 1, 'httpbitlyafelto': 1, 'disappearance': 1, 'imperils': 1, 'backass': 1, 'douche': 1,
             'httpretwtme1msls': 1, 'slowimprove': 1, 'stratosphere': 1, 'wonder': 1, 'briefed': 1,
             'httptrimlink1h8r': 1, 'freak': 1, 'dulles': 1, 'figure': 1, 'italy': 1, 'goodfeed': 1,
             'httpoohjacomxb8s2': 1, 'yes': 1, 'funny': 1, 'lamontkingtv': 1, 'httpbitly7zvxvh': 1, 'sarah': 1,
             'httpowly1duiy': 1, 'investors': 1, 'held': 1, 'publically': 1, 'warns': 1, 'httpbitlybiqnl0': 1,
             'humans': 1, 'videos': 1, 'httpbitlydja0a4': 1, 'approaches': 1, 'cfp': 1, 'httpbitly9pn5of': 1,
             'httpbitlyd1yc1c': 1, 'morales': 1, 'evo': 1, 'dies': 1, 'httpvideopbsorgvideo1305543836': 1, 'turning': 1,
             'tale': 1, 'httplnkms4l7st': 1, 'bishops': 1, 'catholic': 1, 'harmful': 1, 'directly': 1, 'experience': 1,
             'catholicclimate': 1, 'httpbitlycnu2dm': 1, 'blossoms': 1, 'cherry': 1, 'japans': 1, 'abstract': 1,
             'httpbitly8yemsh': 1, 'coldchain': 1, 'httpbitlya3zfhs': 1, 'developmentvohra': 1, 'plays': 1,
             'phenomenon': 1, 'httpowly14iff': 1, 'pictures': 1, 'subject': 1, 'httpbitlydalwzf': 1,
             'heraldofficials': 1, '28': 1, 'httpnxyindxleu': 1, 'httpoohjacomx6gan': 1, 'warmingglobal': 1,
             'httpnytimsaxteyy': 1, 'httptinyurlcomy7q29uk': 1, 'destruction': 1, 'httpsupr2yy1lc': 1, 'president': 1,
             'hereisawayjose': 1, 'huffingtonpost': 1, 'httpbitlycldqgz': 1, 'indicator': 1, 'methane': 1,
             'httpbitlycmovqd': 1, 'general': 1, 'informed': 1, 'supporters': 1, 'party': 1, 'guardianeco': 1,
             'thursday': 1, 'httpoohjacomxbycu': 1, 'sufferingfrom': 1, 'nowim': 1, 'httpoohjacomxbpdv': 1,
             'destiny': 1, 'irreversible': 1, '422': 1, 'httpbitly9cujqk': 1, 'since': 1, 'mckibben': 1, 'changin': 1,
             'httpbitlyblgaf7': 1, 'impactsun': 1, 'httpbitly9hy51b': 1, 'proving': 1, 'hopkins': 1,
             'httpbitlycdq1zj': 1, 'goodfood': 1, 'kcrw': 1, 'httpbitlya8lfpz': 1, 'forming': 1, 'takes': 1, 'phi': 1,
             'httpbitlyccb87d': 1, 'wind': 1, 'httpbitlyazdu0': 1, 'httpbitly9lutki': 1, 'grape': 1, 'delicate': 1,
             'veritas': 1, 'vino': 1, 'httptrimlink1gb8': 1, 'httpdiggcomd21imtot10': 1, 'fortunegreen': 1,
             'chouinard': 1, 'yvon': 1, 'clothing': 1, 'httpowly15g0o': 1, 'gray': 1, 'alters': 1,
             'httpgooglfbaqrum': 1, 'httptwurlnlioewyh': 1, 'httpbitlybl6vep': 1, 'sees': 1, 'opinion': 1,
             'disclosed': 1, 'httpbitly9rrgsg': 1, 'httpbitly9tnk2s': 1, 'washington': 1, 'trust': 1, 'poll4': 1,
             'vrwctexan': 1, 'pres': 1, 'maintain': 1, 'planting': 1, 'looks': 1, 'program': 1, 'indonesia': 1,
             'httpbitlybdd1pp': 1, 'imperative': 1, 'practical': 1, 'lens': 1, 'ethical': 1, 'buffer': 1,
             'everything': 1, 'choose': 1, 'words': 1, 'taken': 1, 'chemicallygreen': 1, 'angelwardriver': 1,
             'httpretwtme1lsun': 1, 'year': 1, '4000': 1, 'nature': 1, 'httpbitly7pjhig': 1, 'wipe': 1, 'moderate': 1,
             'terryacarter': 1, 'earthnews': 1, 'httpbitly9jwccb': 1, 'doodoo': 1, 'christellar': 1,
             'httpretwtme1mskb': 1, 'httpbitly9xfgo8': 1, 'httpbitlyazbbow': 1, '8': 1, 'httpbitlybp2bw4': 1, 'past': 1,
             'adapted': 1, 'hominids': 1, 'goody': 1, 'email': 1, 'send': 1, 'httpbitlydbjniu': 1, 'incontrove': 1,
             'acidic': 1, 'divespot': 1, 'httpbitlycdk39l': 1, 'changeeweekresponding': 1, 'newsnoaa': 1, 'eweek': 1,
             'httpbitlydareyr': 1, 'rad': 1, 'require': 1, 'breaking': 1, 'httpbitlyadhl7l': 1,
             'httpwwwaccuweathercomregionalnewsstoryaspregioneastusnews': 1, 'stormgt': 1, 'updatecontmajor': 1,
             'ericbolling': 1, 'httpurl4eu2hdt2': 1, 'pdigaudio': 1, 'home': 1, 'application': 1, 'thermal': 1,
             'httpretwtme1msip': 1, 'buildup': 1, 'moraqeb': 1, 'httpretwtme1mqj8': 1, 'worldàs': 1,
             'conservalidity': 1, 'httpbitlyaciae3': 1, 'critical': 1, 'threatened': 1, 'listed': 1, 'nunavut': 1,
             'bear': 1, 'polar': 1, 'httpbitlybwdupu': 1, 'thisisourmoment': 1, 'nrdcaf': 1, 'httpxrlusbhgrjo': 1,
             'online': 1, 'available': 1, 'wires': 1, 'yr': 1, 'nino': 1, 'el': 1, 'prob': 1, 'although': 1,
             'package': 1, 'ty': 1, 'larry411': 1, 'apocalypseàonly': 1, 'imminent': 1, 'scenarios': 1, 'nine': 1,
             'httpoohjacomxaw3l': 1, 'httpbitlybxftxz': 1, 'coral': 1, '82': 1, 'threaten': 1, 'wishing': 1,
             'httpbitly9vlo8s': 1, 'httpbitlycuz46u': 1, 'found': 1, 'votegl': 1, 'follow': 1, 'hustings': 1,
             'wwwvoteglobalorguk': 1, 'visit': 1, 'ge2010': 1, 'care': 1, 'stevecockburn': 1, 'planesbut': 1,
             'httpisgd83eln': 1, 'models': 1, 'loveearthalways': 1, 'balmeras': 1, 'nrdc': 1, 'httpbitlyd3bto0': 1,
             'changeing': 1, 'severity': 1, 'warning': 1, 'gsorensen': 1, 'httpbitlycbrpkb': 1, 'minister': 1,
             'httpbitlyac6ngs': 1, 'httpbitlyades0r': 1, 'sucks': 1, 'httpbitlydjzori': 1, 'background': 1, 'cfr': 1,
             'happy': 1, 'httptinyurlcomybqbsv3': 1, 'game': 1, 'httpbitlyac79cz': 1, 'friday': 1, 'nprs': 1,
             'sensibly': 1, 'behave': 1, 'legged': 1, 'indiaits': 1, 'full': 1, 'shown': 1, 'httpoohjacomxakzo': 1,
             'changelighthouse': 1, 'shed': 1, 'httpnprajvq8f': 1, 'intensify': 1, 'nprscience': 1,
             'httpbitlydtkebp': 1, 'woods': 1, 'beneficiaries': 1, 'httpowly162vy': 1, 'contessabrewer': 1,
             'httpbitlycz56b8': 1, 'pachauri': 1, 'labels': 1, 'httpoohjacomxbhwq': 1, 'httpbitly98wi1l': 1, 'blast': 1,
             'httpb': 1, 'literature': 1, 'httpbitlyasui2d': 1, 'po': 1, 'salt': 1, 'denied': 1, 'httpbitlyczya5a': 1,
             'archiv': 1, 'dickens': 1, 'geoffrey': 1, 'dangerous': 1, 'trash': 1, 'cameron': 1, 'urges': 1,
             'matthews': 1, 'ighih': 1, 'httpretwtme1mncb': 1, 'hot': 1, '27': 1, 'httpbitlyalkbne': 1, 'heritage': 1,
             'httpbitlybqi1bm': 1, 'teleport': 1, 'discovers': 1, 'physicist': 1, '2610': 1, 'httpbitlyafiiu5': 1,
             'httpurl4eu2paat': 1, 'httpbitlyd5dmi6': 1, 'destructive': 1, 'truly': 1, 'tlot': 1, 'libertarian': 1,
             'httpbitlydturlg': 1, 'stossel': 1, 'httpbitlyc0b1y5': 1, 'clim': 1, 'presentations': 1, 'loorz': 1,
             'alec': 1, 'theater': 1, 'palace': 1, 'speaks': 1, '15year': 1, 'httpbitly9iwhsq': 1, 'staudt': 1,
             'amanda': 1, 'httpbitlyduqak9': 1, 'workin': 1, 'users': 1, 'computer': 1, 'reminding': 1, 'simple': 1,
             'httpbitlybuyu3l': 1, 'adaptation': 1, 'center': 1, 'httpbitlyatchok': 1, 'httpbitly9dohkw': 1, 'con': 1,
             'massing': 1, 'factors': 1, 'workers': 1, 'retrain': 1, 'httpjmlyfh5uvc': 1, 'communicating': 1,
             'three': 1, 'goodclimatejm': 1, 'httpurl4eu2hdso': 1, 'healthfreaks': 1, 'httpretwtme1mpf2': 1,
             'httpbitly96gwuk': 1, 'climat': 1, 'aimed': 1, 'showcase': 1, 'celebrityfilled': 1, 'exhibition': 1,
             'epsomguardian': 1, 'httpbitlycyv4u0': 1, 'skepticism': 1, 'snomg': 1, 'conflates': 1, 'anyone': 1,
             'unfollow': 1, 'tempted': 1, 'alexlundry': 1, 'habits': 1, 'migrating': 1, 'estimated': 1,
             'rtgreenforyou': 1, 'httpowly1y00p': 1, 'breakdown': 1, '10min': 1, 'awesome': 1, 'pretty': 1,
             'consequence09': 1, 'bit': 1, 'theyre': 1, 'refer': 1, 'wryly': 1, 'amused': 1, 'rather': 1,
             'httpbitlyc2iwya': 1, 'expand': 1, 'urge': 1, 'shore': 1, 'httpbitly9tz9j7': 1, 'ilsen': 1, 'spur': 1,
             'pollutants': 1, 'putting': 1, 'believes': 1, 'giannoulias': 1, 'alexi': 1, 'httpurl4eu31xrk': 1,
             'capital': 1, 'round': 1, 'funding': 1, '91m': 1, 'raises': 1, 'nualight': 1, 'manufacturer': 1,
             'irish': 1, 'httpbitlyabwp35': 1, 'cancer': 1, 'httpbitlycy41h2': 1, 'responsibility': 1, 'celebrities': 1,
             'figures': 1, 'activism': 1, 'kilcher': 1, 'qorianka': 1, 'actress': 1, 'rareplanet': 1,
             'httpretwtme1lwhq': 1, 'underestimated': 1, 'cleantechnica': 1, 'httpretwtme1mqlk': 1,
             'httpbitly9qvt5w': 1, 'httptinyurlcomy252cn2': 1, 'httpawarelaorgp10280': 1, 'manipulating': 1,
             'geoengineering': 1, 'dangers': 1, 'mooney': 1, 'pat': 1, 'nzgreens': 1, 'httpretwtme1mspr': 1,
             'frogblog': 1, 'exposed': 1, 'distortions': 1, 'common': 1, 'httpoohjacomxb8ws': 1, 'httpowly1bezl': 1,
             'products': 1, 'felixsalmon': 1, 'httpowly1beaa': 1, 'hedge': 1, 'httpbitlyc14ze3': 1, 'interwebs': 1,
             'rhetoric': 1, 'chilling': 1, 'httpowly16w7jz': 1, 'earths': 1, 'cochabama': 1, 'httpbitlybklu4h': 1,
             'refuting': 1, 'purportedly': 1, 'finnish': 1, 'sends': 1, 'denialist': 1, 'cute': 1, 'httpbitlybygneg': 1,
             'cars': 1, 'complaints': 1, 'investigate': 1, 'toyota': 1, 'asks': 1, 'japanese': 1, 'httpbitly92kxhl': 1,
             'surprisingly': 1, '09': 1, 'compare': 1, 'assessments': 1, 'intel': 1, 'httpbitly95ceol': 1,
             'allocation': 1, 'httpretwtme1luza': 1, 'ya': 1, 'property': 1, 'oceanfront': 1, 'buy': 1, 'zener39': 1,
             '33': 1, 'httpgooglfbshq49': 1, 'httpbitly9gqobz': 1, 'frontporchforum': 1, 'httpretwtme1lxob': 1,
             'midnight': 1, 'ghost': 1, 'inspiring': 1, 'neighbors': 1, 'httpbitlyct03mg': 1, 'inuits': 1, 'turn': 1,
             'httpbitly9aei0k': 1, 'necessary': 1, 'nationalizing': 1, 'v': 1, 'localities': 1, 'southernmost': 1,
             'httpbitlyd6rppq': 1, 'hideaway': 1, 'altered': 1, 'anymore': 1, 'pond': 1, 'walden': 1,
             'httpbitlybqrlwe': 1, 'greenhour': 1, 'httpunu4gg25': 1, 'degrading': 1, 'honorthysowbug': 1,
             'httpretwtme1lyik': 1, 'fabianpattbergcom': 1, 'tax': 1, 'hood': 1, 'robin': 1, 'politext': 1,
             'httpretwtme1n0pm': 1, 'scnow': 1, 'organization': 1, 'veterans': 1, 'httpbitly9k0yih': 1, 'mongabay': 1,
             'httpretwtme1lrvk': 1, 'rainforest': 1, 'tmclimate': 1, 'httpbitlyc7rkvi': 1, 'preaching': 1, 'fifty': 1,
             'httpbitlycnrt7v': 1, 'maps': 1, 'mind': 1, 'httpurl4eu2r22y': 1, 'httpbitlycg8p6g': 1, 'mines': 1,
             'httpinterconrecyclingcom': 1, 'recycle': 1, 'contributor': 1, 'dioxidea': 1, 'lbs': 1, 'creates': 1,
             'gallon': 1, 'httpbitlyabm7iz': 1, 'httphuffto9xw7kp': 1, 'consc': 1, 'httphuffto9ipdju': 1,
             'httpbitly9m4hji': 1, 'improve': 1, 'nyserda': 1, 'clarkson': 1, 'clarksonuniv': 1, 'httpbitlydp9r2x': 1,
             'httpowly1bqtj': 1, 'havent': 1, 'aaronmorris': 1, 'mims': 1, 'httpbitlyajozgb': 1,
             'httpbitlyecoeconomics': 1, 'httpbitlyarb8gc': 1, 'webinar': 1, 'feb': 1, 'school': 1, 'vermont': 1,
             'parenteau': 1, 'patrick': 1, 'added': 1, 'disasters': 1, 'affected': 1, 'chioxfamaction': 1,
             'cuddlendance': 1, 'httpretwtme1mn2w': 1, 'truth': 1, 'teh': 1, 'glaciergate': 1, 'nowhere': 1, 'gone': 1,
             'midatlantic': 1, 'acting': 1, 'beside': 1, 'sort': 1, 'adam4004': 1, 'demvdaycards': 1, 'hotter': 1,
             'burns': 1, 'children': 1, 'httpbitly9lfhip': 1, 'httpowlyi16qg': 1, 'chicago': 1, 'midapril': 1,
             'tulips': 1, 'httpoohjacomxc5nw': 1, 'arabia': 1, 'culture': 1, 'flood': 1, 'dhabi': 1, 'abu': 1,
             'httpbitly9uytgl': 1, 'rangerrickmag': 1, 'httpretwtme1mtbp': 1, 'inspected': 1, 'httpbitlyd3cakq': 1,
             'natgas': 1, 'opportunities': 1, 'tremendous': 1, 'browner': 1, 'director': 1, 'wh': 1, 'angaus': 1,
             'several': 1, 'every': 1, 'unemployment': 1, 'life': 1, 'persons': 1, 'average': 1, 'httpbitlyc6r4so': 1,
             'statistics': 1, 'httpbitly5ipja': 1, 'ruralpr': 1, 'httpretwtme1mvqr': 1, 'rarewildlifeguy': 1,
             'invasivenotes': 1, 'httpbitlyaciigz': 1, 'snowpocalypses': 1, 'predictions': 1, 'httpustream6nip': 1,
             'beck': 1, 'httpretwtme1mpht': 1, 'feeling': 1, 'stephanbecker': 1, 'httpretwtme1mqtn': 1,
             'httpbitlydbh9lu': 1, 'httpbitlyb6vhx2': 1, 'httpretwtme1n08t': 1, 'quix': 1,
             'biodiversityhttpbitlyb7nudj': 1, 'productive': 1, 'probably': 1, 'moron': 1, 'httpbitly9gtncg': 1,
             '201': 1, '6': 1, 'centre': 1, 'conclusions': 1, 'httpjmpadukuk': 1, 'thedailygreencom': 1, 'kgl': 1,
             'lieberman': 1, 'httpbitlycrplk4': 1, 'brought': 1, 'extinctions': 1, 'mass': 1, 'hubs': 1, 'fuzzy': 1,
             'interagency': 1, 'suggest': 1, 'httpbitlyb7lbwm': 1, 'industries': 1, 'entirely': 1, 'birth': 1,
             'portal': 1, 'httpbitlyavwfkq': 1, 'god': 1, 'dcseth': 1, 'httpbitlycqczsj': 1, 'httpslidesharebrd3bw': 1,
             'animations': 1, 'download': 1, 'midcontinent': 1, 'httpsnytcomuedy': 1, 'monitor': 1, 'network': 1,
             'statewide': 1, 'sets': 1, 'nytimes': 1, 'httpbitlyczdew7': 1, 'plea': 1, 'delong': 1, 'j': 1,
             'bradford': 1, 'prescription': 1, 'delongs': 1, 'brad': 1, 'wilburns': 1, 'httpretwtme1lylo': 1,
             'calculators': 1, 'footprint': 1, 'carbonenvironmental': 1, 'vacation': 1, 'summer': 1, 'extended': 1,
             'doin': 1, 'darn': 1, 'curb': 1, 'verwaayen': 1, 'ben': 1, 'httptinyurlcomygynf5c': 1, 'africa2day': 1,
             'httpbitlyd5si4f': 1, 'httpbitlydgwtf0': 1, 'delay': 1, 'envnewsnet': 1, 'httpz3igztk': 1,
             'httpbitlyc6inlw': 1, 'negotiations': 1, 'forward': 1, 'climatebuzz': 1, 'httpbitlybsvevw': 1,
             'httpbitlybsorwh': 1, 'unveile': 1, 'revised': 1, 'unveiled': 1, 'wisconsins': 1, 'httpbitlyaaclxa': 1,
             'arises': 1, 'longstanding': 1, 'httpbitlycjm3xp': 1, 'snowfall': 1, 'brewer': 1, 'httpbitlyca5bom': 1,
             'httpbitlycutiiv': 1, 'httpnxyinh4e3z': 1, 'httpbitlyck46hy': 1, 'complete': 1, 'progress': 1,
             'forestry': 1, 'httptrimmkl6': 1, 'growth': 1, 'ecologists': 1, 'gisforester': 1, 'httpbitly9uuke6': 1,
             'agreement': 1, 'httpbitlyapyoic': 1, 'httpbitlyarcddg': 1, 'warmi': 1, 'regulations': 1, 'draconian': 1,
             'impose': 1, 'rush': 1, 'blow': 1, 'newest': 1, 'idiot': 1, 'bet': 1, 'andrewbreitbart': 1,
             'briandevine': 1, 'gt': 1, 'dishonest': 1, 'httpxrlusbhguwc': 1, 'whys': 1, 'whats': 1, 'hows': 1,
             'communitiesoverview': 1, 'studies': 1, 'httpbitlyat8cgk': 1, 'smh': 1, 'gear': 1, 'meteorology': 1,
             'httpbitly9ew0iz': 1, 'httpbitlydbkxch': 1, 'proble': 1, 'httpwwwenncomecosystemsarticle40994': 1,
             'enncom': 1, 'calacademy': 1, 'httpretwtme1mx7w': 1, 'sciences': 1, 'academy': 1, 'httpurl4eu2mhri': 1,
             'httpurl4eu2cq8w': 1, 'httpoohjacomxc60u': 1, 'associated': 1, 'warmer': 1, 'mosquitofishthe': 1,
             'aids': 1, 'httpbitlycndjvb': 1, 'excess': 1, 'somerfield': 1, 'www350orgbolivia': 1, 'pauljimerson': 1,
             'active': 1, 'namibia': 1, 'httpwwwenvironmentportalinnode302549': 1, 'contribution': 1, 'computing': 1,
             'indiaenvportal': 1, 'alt': 1, 'mine': 1, 'httpretwtme1mqpp': 1, 'skep': 1, 'blitz': 1, 'goes': 1,
             'chronicle': 1, 'houston': 1, 'httpbitlydmkiml': 1, 'liars': 1, 'skeptics': 1, 'prince': 1,
             'httpbitlya1rqht': 1, 'farming': 1, 'httppingfm5wj6n': 1, 'planets': 1, 'prevent': 1, 'httpbitlydq2iui': 1,
             'tu': 1, 'engineer': 1, 'matais': 1, 'dk': 1, 'httpbitlybwagvt': 1, 'fathers': 1, 'repeating': 1,
             'hobart': 1, 'spreads': 1, 'cousteau': 1, 'httpbitlybz4fqj': 1, 'pablo': 1, 'charts': 1, 'includes': 1,
             'httpgoogl8sq9': 1, 'redstate': 1, 'vladimirs': 1, 'buenetwork': 1, 'httpretwtme1mzll': 1, 'victim': 1,
             'shouldnt': 1, 'httpbitlyb5jldk': 1, 'reductions': 1, 'steep': 1, 'positioned': 1, 'massachusetts': 1,
             'httpbitlyc0cj8w': 1, 'unveil': 1, 'ford': 1, 'httpbitlyd0o3xa': 1, 'httpbitlycywhly': 1, 'hazards': 1,
             'processes': 1, 'tend': 1, 'allochthonous': 1, 'httpbmpostcom8751': 1, 'ct': 1, 'chrisdodd': 1,
             'httpbitlydburhs': 1, 'httpwwwthepetitionsitecomtakeaction820159630': 1, 'cifamerica': 1,
             'httpretwtme1mwur': 1, 'gua': 1, 'comment': 1, 'huffhannon': 1, 'joseph': 1, 'httpbitlyb0kvew': 1,
             'possible': 1, 'httptinyurlcomyycupus': 1, 'ltgt': 1, 'heres': 1, 'andychrism': 1, 'httpbitlyc1fl3g': 1,
             'httpowly1onysr': 1, 'true': 1, 'paying': 1, 'cos': 1, 'httpbitlybtyneh': 1, 'httpbitly9psimg': 1,
             'revenueneutral': 1, 'httpbitlywolverinedecline': 1, 'ecopreservation': 1, 'extinct': 1, 'thoreau': 1,
             'ones': 1, 'favors': 1, 'heidiames': 1, 'httpbitlydpak9s': 1, 'regional': 1, 'twoday': 1, 'visayas': 1,
             'concerns': 1, 'wv': 1, 'csrint': 1, 'httpretwtme1msfu': 1, 'waking': 1, 'spanish': 1,
             'httpbitlyddyxmx': 1, 'regimeà': 1, 'àglobal': 1, 'document': 1, 'httpbitlyd3efub': 1, 'greenhous': 1,
             'archive': 1, 'httpbitlybimjco': 1, 'angry': 1, 'httpcligsdpd0m': 1, 'bipartisan': 1, 'envirolib': 1,
             'paulinema': 1, 'httpretwtme1mo0l': 1, 'httpowly15ytv': 1, 'contradiction': 1, 'httpekwirecom': 1,
             'httpgooglfbr0qcd': 1, 'winds': 1, 'httpbitlyc4ncxg': 1, 'driven': 1, 'growing': 1, 'digg': 1,
             'diggatomicpoet': 1, 'httpbitlydmpyre': 1, 'alliance': 1, 'nevada': 1, 'sierra': 1, 'wyss': 1, 'rs': 1,
             'httpbitlydlqgdy': 1, 'httpbitlydredc4': 1, 'documentry': 1, 'hitting': 1, 'front': 1, 'httpbitly61n0u': 1,
             'board': 1, 'edf': 1, 'excellent': 1, 'attended': 1, 'examinercom': 1, 'montanas': 1, 'park': 1,
             'threatening': 1, 'climategroup': 1, 'httpwwwtheclimategrouporg': 1, 'organizations': 1, 'helps': 1,
             'absorb': 1, 'birthday': 1, 'tip': 1, 'httpbitlybcezbs': 1, 'fallen': 1, 'complains': 1, 'katz': 1,
             'ian': 1, 'proponent': 1, 'activist': 1, 'mikerwithcrc': 1, 'httpbitlycn013j': 1, 'discotech': 1,
             'blinking': 1, 'whole': 1, 'bell': 1, 'alarm': 1, 'pen': 1, 'hague': 1, 'frederic': 1, 'stuff': 1,
             'excuse': 1, 'itd': 1, 'survivalist': 1, 'annoys': 1, 'ps': 1, 'beardlace': 1, 'httpretwtme1luk2': 1,
             'desperate': 1, 'organisers': 1, 'httpoohjacomxc5vr': 1, 'intense': 1, 'including': 1, 'worsening': 1,
             'bridge': 1, 'securityvietnamnet': 1, 'chaotic': 1, 'httpsharesm7n1x': 1, 'httpbitly4bvajw': 1, 'frame': 1,
             'reference': 1, 'httpdrudgetw9oxilz': 1, 'mag': 1, 'happen': 1, 'talk': 1, 'httpbitlycevlmr': 1, 'sens': 1,
             'swamp': 1, 'awful': 1, 'httpbitlyav0ldf': 1, 'chapter': 1, 'next': 1, 'httpretwtme1mslg': 1,
             'httpbitly9y8rsq': 1, 'instruments': 1, 'httpretwtme1lvbf': 1, 'httptlgds8rd6': 1, 'hrhsar': 1,
             'sigsforyou': 1, 'wing': 1, 'fears': 1, 'crazy': 1, 'play': 1, 'police': 1, 'audi': 1,
             'httptinyurlcomy2zhsve': 1, 'meds': 1, 'antiallergy': 1, 'makers': 1, 'michaellemonick': 1,
             'httpbitly9c04zs': 1, 'httpbitly9yvwhz': 1, 'negative': 1, 'refineries': 1, 'cites': 1, 'dcupdates': 1,
             'imgoph': 1, 'admits': 1, 'jimdemint': 1, 'snowing': 1, 'globalwarning': 1, 'httpbitly5xa0tb': 1,
             'davids': 1, 'laurie': 1, 'httpbitlydefx2i': 1, 'graphs': 1, '29': 1, 'httpnytimscuy4y8': 1, 'paul': 1,
             'nyt': 1, 'httpbitlychyuwu': 1, 'cutting': 1, 'denying': 1, 'members': 1, 'wmd': 1, 'iraqi': 1, 'bush': 1,
             'shilling': 1, 'editors': 1, 'elites': 1, 'peterdaou': 1, 'httpbitlydrr5xm': 1, 'hidden': 1, 'romero': 1,
             'robby': 1, 'redman0380': 1, 'dakotarene': 1, 'httpisgd7hoam': 1, 'ru2cool2care': 1, 'vcnaa': 1,
             'eyjafjoell': 1, 'warmingàs': 1, 'materials': 1, 'porous': 1, 'httpbitlyc7z75n': 1, 'httpbitly9m44ej': 1,
             'esg': 1, 'httpbitlybpm7kx': 1, 'httptwurlnlf0aqb3': 1, 'awaken': 1, 'httpbitly94d2xv': 1,
             'httpbitlybebgde': 1, 'fair': 1, 'third': 1, 'httpbitly9asqdr': 1, 'consideration': 1, 'waterfront': 1,
             'citys': 1, 'crises': 1, 'exacerbating': 1, 'hahaha': 1, 'crappy': 1, 'arthuryanb': 1, 'httpsupr1fg7ev': 1,
             'httpbitlybg1dir': 1, 'httpowly16vxyn': 1, 'regul': 1, 'activists': 1}
denial = {'global': 182, 'warming': 177, 'climate': 59, 'rt': 52, 'change': 50, 'gore': 24, 'al': 23, 'snow': 22,
          'science': 21, 'tcot': 20, 'hoax': 12, 'via': 11, 'dc': 10, 'another': 9, 'scam': 8, 'weather': 8,
          'scientific': 8, 'great': 8, 'time': 8, 'link': 7, 'like': 7, 'obama': 7, 'p2': 7, 'skeptics': 7, 'fraud': 7,
          'new': 7, 'made': 7, 'climategate': 7, 'winter': 6, 'still': 6, 'much': 6, 'manmade': 6, 'tlot': 6, 'sgp': 6,
          'collapse': 6, 'conspiracy': 6, 'man': 6, 'silly': 5, 'safety': 5, 'know': 5, 'agree': 5, 'climatechange': 5,
          'public': 5, 'ipcc': 5, 'see': 5, 'hey': 5, 'believe': 5, 'people': 5, 'news': 5, 'get': 5, 'p': 5, 'sign': 5,
          'storm': 5, 'cold': 5, 'blizzard': 5, 'algore': 4, 'make': 4, 'green': 4, 'message': 4, '2': 4, 'exist': 4,
          'think': 4, 'illegal': 4, 'dont': 4, 'energy': 4, 'report': 4, 'lake': 4, 'ucot': 4, 'gop': 4, 'bad': 4,
          'study': 4, 'ass': 4, 'ocra': 4, 'teaparty': 4, 'fast': 4, 'fading': 4, 'consensus': 4, 'bogus': 4,
          'imminent': 4, 'heavily': 4, 'snows': 4, 'explain': 4, 'yearwhere': 4, 'washingtonthird': 4, 'historic': 4,
          'come': 4, 'keep': 4, 'going': 4, 'real': 4, 'media': 4, 'wheres': 4, 'lol': 4, 'snowstorm': 3, 'mine': 3,
          'care': 3, 'hearing': 3, 'senate': 3, 'fact': 3, 'blankenship': 3, 'taxes': 3, 'gorepalin': 3, 'hacks': 3,
          'algores': 3, 'otoolefan': 3, 'flipbooks': 3, 'full': 3, 'tell': 3, 'someone': 3, 'love': 3, 'graham': 3,
          'ever': 3, 'liberal': 3, 'degrees': 3, 'saying': 3, 'gov': 3, 'due': 3, 'scientists': 3, 'please': 3,
          'theories': 3, 'gores': 3, 'morning': 3, 'cant': 3, 'theory': 3, 'sense': 3, 'doesnt': 3, 'proves': 3,
          'disaster': 3, 'prius': 3, 'stephenathome': 3, 'corrupted': 3, 'fanatics': 3, 'barone': 3, 'michael': 3,
          'snomg': 3, 'also': 3, 'washington': 3, 'proof': 3, 'tycot': 3, 'tornadocot': 3, 'mississippi': 3,
          'across': 3, 'racing': 3, 'tornadoes': 3, 'virgiltexas': 3, 'contradict': 3, 'storms': 3, 'hannity': 3,
          'mean': 3, 'evidence': 3, 'show': 3, 'junk': 3, 'major': 3, 'o': 3, 'farce': 3, 'justinbiebersucks': 3,
          'warmingclimate': 3, 'good': 3, 'crisis': 3, 'newtgingrich': 3, 'tht': 2, 'demand': 2, '2nd': 2, 'sht': 2,
          'execs': 2, 'goldman': 2, 'foxandfriends': 2, 'fairy': 2, 'scum': 2, 'need': 2, 'useful': 2, 'power': 2,
          'help': 2, 'working': 2, 'regulation': 2, 'calls': 2, 'r': 2, 'peace': 2, 'paper': 2, 'snowpocalypse': 2,
          'america': 2, 'epic': 2, 'httpbitlyauupbl': 2, 'nascar': 2, 'imaginary': 2, 'lectured': 2, 'motorsports': 2,
          'watch': 2, 'suggest': 2, 'politely': 2, 'let': 2, 'alms': 2, 'could': 2, 'true': 2, 'idiots': 2, 'never': 2,
          'decline': 2, 'hide': 2, 'give': 2, 'amazing': 2, 'u': 2, 'either': 2, 'cancelled': 2, 'caused': 2, '1995': 2,
          'since': 2, 'advocates': 2, 'uns': 2, 'day': 2, 'wish': 2, 'control': 2, 'population': 2, 'utah': 2,
          'httpbitlycwrejl': 2, 'bbc': 2, 'sceptical': 2, 'increasingly': 2, 'become': 2, 'british': 2, 'fuck': 2,
          'tax': 2, 'regulators': 2, 'scamed': 2, 'community': 2, 'finally': 2, 'laws': 2, 'committee': 2, 'house': 2,
          'rise': 2, 'panel': 2, 'pollution': 2, 'houston': 2, 'lie': 2, 'lindsay': 2, 'watching': 2, 'billion': 2,
          'close': 2, 'worth': 2, 'credits': 2, 'decade': 2, 'award': 2, 'artist': 2, 'fat': 2, 'truly': 2, 'fuel': 2,
          'video': 2, 'author': 2, 'property': 2, 'copyrighted': 2, 'contents': 2, 'heat': 2, '423': 2, 'ca': 2,
          '52': 2, 'dear': 2, 'every': 2, 'really': 2, 'press': 2, 'cut': 2, 'waste': 2, 'planet': 2, 'didnt': 2,
          'needs': 2, 'hmmm': 2, 'psiryu': 2, 'warm': 2, 'ground': 2, 'blaming': 2, 'glory': 2, 'current': 2, 'w': 2,
          'explains': 2, 'mail': 2, 'globe': 2, 'torontos': 2, 'wente': 2, 'margaret': 2, 'un': 2, 'death': 2,
          'election': 2, 'platform': 2, 'campaign': 2, 'main': 2, 'warmingmy': 2, 'myth': 2, 'war': 2, 'funding': 2,
          'would': 2, 'coast': 2, 'east': 2, 'blizzards': 2, 'causes': 2, 'thought': 2, 'answer': 2, 'scandal': 2,
          'behind': 2, 'left': 2, 'httpowly15udj': 2, '2007': 2, 'using': 2, 'matters': 2, 'ha': 2, 'record': 2,
          'falls': 2, 'fractures': 2, 'glacier': 2, 'peruvian': 2, 'created': 2, 'tsunami': 2, 'killer': 2, '75ft': 2,
          'jazgar': 2, 'theres': 2, 'hysteria': 2, 'conditioners': 2, 'air': 2, 'sell': 2, 'order': 2, 'ge': 2,
          'perpetrated': 2, 'international': 2, 'talk': 2, 'political': 2, 'graph': 2, 'ruse': 2, 'thing': 2, 'next': 2,
          'data': 2, 'office': 2, 'advertisements': 2, 'buying': 2, 'siemens': 2, 'boycott': 2, 'back': 2,
          'globalwarming': 2, 'th': 2, 'far': 2, 'inches': 2, 'got': 2, 'uncle': 2, 'cries': 2, 'snowing': 2,
          'jimdemint': 2, 'disproving': 2, 'snowmageddon': 2, 'us': 2, 'ask': 2, 'gt': 2, 'happened': 2,
          'httpblogschroncomtxpotomac201002richgalenisglobalwarmingahtml': 1, 'job': 1, 'galen': 1, 'rich': 1,
          'spain': 1, 'solar': 1, 'jmac82': 1, 'thr': 1, 'fortunate': 1, 'fungus': 1, 'toe': 1, 'auth': 1,
          'newfederalists': 1, 'anthropagenic': 1, 'religion': 1, 'islam': 1, 'amspec': 1, 'agw': 1,
          'httpbitlyagvvio': 1, 'alarmism': 1, 'unsubstantiated': 1, 'underbelly': 1, 'soft': 1, 'attack': 1,
          'snowin': 1, 'evrywk': 1, 'life': 1, 'seen': 1, 'produced': 1, 'season': 1, 'brother': 1, 'step': 1,
          'httpbitly9xlmwu': 1, 'exposed': 1, 'claim': 1, 'false': 1, 'httptinyurlcomy4f7m8m': 1, 'exaggerated': 1,
          'slammed': 1, 'temperature': 1, 'stick': 1, 'hockey': 1, 'ice': 1, 'attacked': 1, 'emmzee': 1,
          'httpbitly9trngu': 1, 'tied': 1, 'e': 1, 'rosannemf': 1, 'thanks': 1, 'httpwwwclimatedepotcom': 1,
          'crapola': 1, 'exposing': 1, 'httpbitlyd34d8y': 1, 'vindicated': 1, 'sceptics': 1, 'cools': 1, 'factdid': 1,
          'myronanderson': 1, 'summer': 1, 'coolest': 1, 'soo': 1, 'httptinyurlcomyks75n5': 1, 'mock': 1, 'use': 1,
          'conservatives': 1, 'cbs': 1, 'snowed': 1, 'council': 1, 'obumers': 1, 'subject': 1, 'globeandmail': 1,
          'httptgamcahrh': 1, 'perks': 1, 'congressional': 1, 'referring': 1, 'truth': 1, 'distortion': 1, 'whiche': 1,
          'vballr4life7': 1, 'fu': 1, 'coldest': 1, 'live': 1, 'read': 1, 'spring': 1, '30s': 1, 'turn': 1, 'call': 1,
          'barackborat': 1, 'nycaviation': 1, 'thats': 1, 'bother': 1, 'research': 1, 'paying': 1, 'mind': 1,
          'mikekruger': 1, 'bobsyouruncle': 1, 'httptinyurlcomkrwusz': 1, 'tale': 1, 'keder': 1, 'shocking': 1,
          'honest': 1, 'mmfa': 1, 'gotta': 1, 'result': 1, 'mag': 1, 'according': 1, 'crablover7': 1, 'internet': 1,
          'invented': 1, 'thinks': 1, 'gig': 1, 'wont': 1, 'dennylonergan': 1, 'warmers': 1, 'http2eyfslpt': 1,
          'postponed': 1, 'impacts': 1, 'epw': 1, 'irony': 1, 'dripping': 1, 'miners': 1, 'dead': 1, '29': 1,
          'massey': 1, 'idea': 1, 'patrickc': 1, 'already': 1, 'stop': 1, 'agency': 1, 'federal': 1, 'july': 1,
          'remind': 1, 'said': 1, 'act': 1, 'mlmoore2': 1, 'days': 1, 'within': 1, 'butt': 1, 'grrrrglobal': 1,
          'snowmaggedon': 1, 'httpbitlybclzes': 1, 'httpsharesanasc': 1, 'gopusa': 1, 'lives': 1, 'changeit': 1,
          'adapt': 1, 'businesses': 1, 'governments': 1, 'serviceto': 1, 'noaa': 1, 'creates': 1, 'httpbitlycn8jen': 1,
          'yet': 1, 'bringing': 1, 'leftwing': 1, 'reinforces': 1, 'nature': 1, 'mother': 1, 'os': 1, 'way': 1,
          'natures': 1, '1kevgriff': 1, 'urinate': 1, 'nyc': 1, '40': 1, '1014': 1, 'supposed': 1, 'tonight': 1,
          'car': 1, 'dust': 1, 'sprinkle': 1, 'anyway': 1, 'bull': 1, 'oh': 1, 'cooling': 1, 'blamed': 1, 'oxchris': 1,
          'httpbitly9swo7u': 1, 'views': 1, 'represent': 1, 'probably': 1, 'cal': 1, 'hypothosys': 1, 'initiated': 1,
          'ones': 1, 'disproved': 1, 'stupid': 1, 'voted': 1, 'morons': 1, 'drag': 1, 'snowplow': 1, 'front': 1,
          'tie': 1, 'plain': 1, 'team': 1, 'im': 1, 'htink': 1, 'sorry': 1, 'fml': 1, '1420': 1, 'syancyfox5': 1,
          'heads': 1, 'headsand': 1, 'realism': 1, 'note': 1, 'offers': 1, 'revkin': 1, 'met': 1, 'pen': 1,
          'warmingfail': 1, 'beer': 1, 'least': 1, 'fun': 1, 'davidcorndc': 1, 'httpowly15sfq': 1, 'httpekwirecom': 1,
          'httpbitlyb6lkba': 1, 'enabled': 1, 'watchdog': 1, 'httpbitlyabmsjt': 1, 'untrustworthy': 1,
          'intergovernmental': 1, 'abandons': 1, 'india': 1, 'httpowly1cifw': 1, 'cnsnewscom': 1, 'dream': 1,
          'totalitarians': 1, 'theologian': 1, 'httphufftoas7elo': 1, 'rules': 1, 'ceo': 1, 'coal': 1,
          'httpbitly9s5oaz': 1, 'nonfiction': 1, '8': 1, 'amazon': 1, '28': 1, 'ranked': 1, 'currently': 1,
          'bestseller': 1, 'blunder': 1, 'mr': 1, 'hows': 1, 'area': 1, 'cookederready': 1, 'almost': 1, 'numbers': 1,
          'hard': 1, 'anglia': 1, 'assured': 1, 'nathanwurtzel': 1, 'efforts': 1, 'jokes': 1, 'httpbitly9w0szn': 1,
          'takes': 1, 'httpbitlybytsem': 1, 'fighting': 1, 'switch': 1, 'folks': 1, 'rebeccawalker': 1,
          'httpbitlycgfw4o': 1, 'speaks': 1, 'member': 1, 'rejects': 1, 'society': 1, 'geological': 1, 'breaking': 1,
          'httpbitlydx5ri6': 1, 'eh': 1, '4': 1, 'gets': 1, 'breaks': 1, 'b4': 1, 'enjoying': 1, 'thanxhope': 1,
          'well': 1, 'v': 1, 'gt1802': 1, 'httpbitlyaffkez': 1, 'crime': 1, 'guilty': 1, 'youd': 1, 'deny': 1,
          'tolerant': 1, 'gbjoe': 1, 'httpbitlyamrmtg': 1, 'physics': 1, 'basic': 1, 'violates': 1, 'debunking': 1,
          'physicists': 1, 'two': 1, 'redostoneage': 1, 'transported': 1, 'activist': 1, 'arctic': 1, 'rescued': 1,
          'warmist': 1, 'va': 1, 'httptwitpiccom12fel9': 1, 'effects': 1, 'latin': 1, 'skepticism': 1, 'icot': 1,
          'http1xorglw684': 1, 'poblaciñn': 1, 'y': 1, 'climàtico': 1, 'cambio': 1, 'sminfowars': 1,
          'httpretwtme1lusx': 1, 'lawmaker': 1, 'httpbitlydfxl79': 1, 'supported': 1, 'relevant': 1, 'apparently': 1,
          'climatescam': 1, 'httpsharesmcivt': 1, 'lemmings': 1, 'mancaused': 1, 'fantasy': 1, 'perpetuate': 1,
          'continue': 1, 'vp': 1, 'former': 1, 'sounds': 1, 'httpbitlyffpgy': 1, 'online': 1, 'times': 1, 'autism': 1,
          'fixed': 1, 'wakefield': 1, 'andrew': 1, 'doctor': 1, 'mmr': 1, 'world': 1, 'lying': 1, 'policy': 1,
          'jobs': 1, 'nut': 1, 'jercope': 1, 'httpretwtme1lygj': 1, 'solveclimatecom': 1, 'implying': 1,
          'resolution': 1, 'passes': 1, 'seriouly': 1, 'lies': 1, 'lowkell': 1, 'belive': 1, 'experts': 1,
          'forensics': 1, 'computer': 1, 'opinion': 1, 'regard': 1, 'little': 1, 'pursued': 1, 'agenda': 1,
          'publicpolicy': 1, 'httpbitlyaobxji': 1, 'immigration': 1, 'bill': 1, 'move': 1, 'set': 1, 'reid': 1,
          'co2hog': 1, 'sick': 1, 'guys': 1, 'httpowly1bikz': 1, 'credibility': 1, 'networks': 1, 'special': 1,
          'newsbusters': 1, 'cbiz': 1, 'rectum': 1, 'relieffrom': 1, 'huge': 1, 'sighs': 1, 'httpbitlyddshde': 1,
          'exonerated': 1, 'farts': 1, 'cow': 1, 'tommorow': 1, 'lot': 1, 'shoveling': 1, 'gonna': 1, 'linking': 1,
          'excuse': 1, 'brained': 1, 'hair': 1, 'time2': 1, 'groupies': 1, 'egores': 1, 'niteowl223': 1, 'bunk': 1,
          'reaffirmations': 1, 'astute': 1, 'reading': 1, 'law': 1, 'kerry': 1, 'john': 1, 'bs': 1, 'health': 1,
          'pushing': 1, 'ok': 1, 'robpas': 1, 'blano': 1, 'agreed': 1, 'httpmylocme3fmvx': 1, 'worshipers': 1,
          'expense': 1, 'humor': 1, 'god': 1, 'causing': 1, 'volcano': 1, 'upset': 1, 'isnt': 1, 'lemme': 1, 'aint': 1,
          'stuff': 1, 'fox': 1, 'httpdrudgetwdyawzc': 1, 'drudgereport': 1, 'course': 1, 'yes': 1, 'hell': 1,
          'httptwitpiccom11s6eq': 1, 'rosed1st1': 1, 'dnoxon': 1, 'alarmists': 1, 'pic': 1, 'duped': 1, 'lied': 1,
          'huh': 1, 'sharifkouddous': 1, 'httpbitlydyfhdy': 1, 'mistakes': 1, 'admitted': 1, 'chief': 1, 'process': 1,
          'speed': 1, 'per': 1, 'aquanet': 1, 'cans': 1, '3': 1, 'used': 1, 'girls': 1, '1020': 1, 'warning': 1,
          'httpbitlyakeaxp': 1, 'thi': 1, 'making': 1, 'golfers': 1, 'fortynine': 1, 'twentyfive': 1, 'dare': 1,
          'golfer': 1, 'oneeyed': 1, 'survivalstation': 1, 'httpbitlyc9nvkk': 1, 'propaganda': 1, 'disbelieve': 1,
          'majority': 1, 'httpdlvrit1qqw': 1, 'aimed': 1, 'claims': 1, 'representative': 1, 'state': 1,
          'httpwwwspectatorcoukprintpoliticsall5749853theglobalwarmingguerrillasthtml': 1, 'spectator': 1, 'ridley': 1,
          'matt': 1, 'httpbitlyackz8j': 1, 'politics': 1, 'fail': 1, 'says': 1, 'history': 1, 'growth': 1,
          'economic': 1, 'approach': 1, 'ignore': 1, 'cuts': 1, 'try': 1, 'mattyglesias': 1, 'httpbitly9fuavy': 1,
          'httpowly173j7l': 1, 'called': 1, 'raise': 1, 'families': 1, 'destroy': 1, 'evolution': 1, 'one': 1,
          'tectonics': 1, 'plate': 1, 'kagrox': 1, 'naaahhhaaaa': 1, 'brainwashing': 1, 'understand': 1, 'philly': 1,
          'sheeple': 1, 'httpoohjacomx6nkh': 1, 'strong': 1, 'send': 1, 'want': 1, 'lawmakers': 1, 'utahutah': 1,
          'seeks': 1, 'signs': 1, 'nutjobs': 1, 'httpbitly8fdctw': 1, 'telegraph': 1, 'disasters': 1, 'natural': 1,
          'linked': 1, 'incorrectly': 1, 'timmontgomerie': 1, 'httpretwtme1luey': 1, 'debate': 1, 'losing': 1,
          'followers': 1, 'centreright': 1, 'httptinyurlcom3yjklo8': 1, 'culturemap': 1, 'alarmist': 1, 'talks': 1,
          'expert': 1, 'httpbitlycw6qj8': 1, 'vodpod': 1, 'interview': 1, 'daleo': 1, 'joseph': 1, 'httpbitly9w8rhw': 1,
          'proven': 1, 'getting': 1, 'billwilsonalg': 1, 'old': 1, 'year': 1, '110': 1, 'broke': 1, 'snowiest': 1,
          'mmorg9yd': 1, 'yippie': 1, 'thaw2009': 1, 'movie': 1, 'horror': 1, 'httpbitlycblw6t': 1, 'timeinc': 1,
          'question': 1, 'httpbitly92nl1d': 1, 'right': 1, 'vacation': 1, 'guess': 1, 'earthday': 1,
          'httpbitly9e8ohk': 1, 'hype': 1, 'challenge': 1, 'reasonable': 1, 'nice': 1, 'httpbitly9jozba': 1,
          'proponents': 1, 'discredits': 1, 'alone': 1, 'observation': 1, 'common': 1, 'httpbitlybfhwbw': 1,
          'oxburgh': 1, 'quotes': 1, 'balancing': 1, 'phenomena': 1, 'weird': 1, 'stay': 1, 'haha': 1, 'allycouture': 1,
          'ii': 1, 'modeling': 1, 'niche': 1, 'analysis': 1, 'logical': 1, 'httptrimnn7p': 1, 'clueless': 1,
          'tracker': 1, 'announce': 1, 'conference': 1, 'administration': 1, 'ft': 1, 'httpbitlydrrein': 1, 'story': 1,
          'httpbitly94dptq': 1, 'pretending': 1, 'surplus': 1, 'catastrophe': 1, 'httpisgdbrylo': 1, 'fund': 1,
          'njs': 1, 'million': 1, '65': 1, 'christie': 1, 'cubachi': 1, 'hero': 1, 'suspended': 1, 'httpbitlydzikfa': 1,
          'httpowly13pnw': 1, 'townhallcom': 1, 'httpbitlyalsn33': 1, 'wind': 1, 'minnesota': 1, 'frozen': 1,
          'turbines': 1, 'moneyglobal': 1, 'stimulus': 1, 'fucking': 1, 'wasnt': 1, 'pluto': 1, 'trust': 1, 'asap': 1,
          'respond': 1, 'calling': 1, 'httpdlvrit1c2p': 1, 'hysterical': 1, 'seem': 1, 'whiners': 1, 'stories': 1,
          '100s': 1, 'march': 1, 'nikkibama': 1, 'hhrs': 1, 'warmingidiots': 1, 'liberals': 1, 'unbelievable': 1,
          'tribbles': 1, 'tami': 1, 'tamij': 1, 'httpmylocme3fmls': 1, 'credence': 1, 'gives': 1, 'anyone': 1,
          'support': 1, 'newt': 1, 'conservativela': 1, 'httpoohjacomx6yji': 1, 'distortions': 1, 'based': 1,
          'datamuch': 1, 'challenges': 1, 'horner': 1, 'httpbitlyd2510l': 1, 'makes': 1, 'nasa': 1, 'httpcligss5bjh': 1,
          'horrible': 1, 'dying': 1, 'lizarddawg': 1, 'httpoohjacomxbqai': 1, 'activists': 1, 'displeased': 1,
          'group': 1, 'cheaper': 1, 'bears': 1, 'polar': 1, 'heated': 1, 'moving': 1, 'money': 1, 'spend': 1, 'id': 1,
          'pir8gold': 1, 'httpbitly9ykqbr': 1, 'column': 1, 'towhhall': 1, 'electar2010': 1, '3wordslibshate': 1,
          'claiming': 1, 'today': 1, 'suspects': 1, 'usual': 1, 'hear': 1, 'httpowly1czfa': 1, 'suvs': 1,
          'questions': 1, 'may': 1, 'volcanoes': 1, 'icecovered': 1, 'brrr': 1, 'boo': 1, 'brr': 1, 'apocolypse': 1,
          'edenjames': 1, 'httptinyurlcomyzxap7c': 1, 'failure': 1, 'journalistic': 1, 'massive': 1, 'steyn': 1,
          'mark': 1, 'httpffimjx0or': 1, 'official': 1, 'profiteering': 1, 'httpbitlybiuip0': 1, 'scare': 1,
          'shabby': 1, 'regarding': 1, 'uninformed': 1, 'quite': 1, 'remains': 1, 'american': 1, 'facts': 1, 'pesky': 1,
          'interested': 1, 'undeniable': 1, 'emperorbob': 1, 'clue': 1, 'unemployed': 1, 'believing': 1, 'graduate': 1,
          'youll': 1, 'disappointment': 1, 'campus': 1, 'hitler': 1, 'slyty17': 1, 'arkiebrian': 1,
          'httpbitlycdttyk': 1, 'fabricate': 1, 'near': 1, 'view': 1, 'terra': 1, 'httptwitpiccom11zs79': 1, 'du1': 1,
          'dnj': 1, 'httpbitly96xkoi': 1, 'sean': 1, 'digg': 1, 'plz': 1, 'httpbitly8yzbe0': 1, 'curr': 1, 'reviews': 1,
          '102': 1, 'rating': 1, 'average': 1, 'brand': 1, 'leads': 1, 'confusion': 1, 'rock': 1, 'alaska': 1,
          'httpbitlyaeawkv': 1, 'httpbitlyao6fql': 1, 'gemstars': 1, 'melts': 1, 'totally': 1, 'yeah': 1, 'fiction': 1,
          'discuss': 1, 'shows': 1, 'c4l': 1, 'yal': 1, 'bolivia': 1, 'httptinyurlcomy6679sm': 1, 'davidtheroux': 1,
          'httptinyurlcomyjj5ovp': 1, 'president': 1, 'busted': 1, 'httpbitly9vq30k': 1, 'climatedebate': 1,
          'yeahglobal': 1, 'httpbitlydrk1ha': 1, 'unravels': 1, 'monoxide': 1, 'dihydrogen': 1, 'blame': 1, 'theyre': 1,
          'ahhphotography': 1, 'knew': 1, 'commentator': 1, 'httpbitly9mjlot': 1, 'intellectuals': 1, 'manufactured': 1,
          'sowell': 1, 'thomas': 1, 'youtube': 1, 'ccfeditor': 1, 'httpretwtme1mxlv': 1, 'treason': 1, 'capandtrade': 1,
          'httpbitlyaqhjex': 1, 'years': 1, '20': 1, 'manipulated': 1, 'grin': 1, 'httpbitlycjiqdh': 1, 'feds': 1,
          'announcement': 1, 'rearranges': 1, 'blizzrd': 1, 'federallobbyist': 1, 'httpgooglfbtowc': 1, 'dcexaminer': 1,
          'settled': 1, 'ltlt': 1, 'reality': 1, 'httptwitpwrcomdev': 1, 'joelcomm': 1, 'sink': 1, 'starting': 1,
          'seems': 1, 'httpgooglfbytii': 1, 'conservative': 1, 'admit': 1, 'robport': 1, 'eddriscoll': 1,
          'environmentalists': 1, 'bug': 1, 'hum': 1, 'yetas': 1, 'poconosmuch': 1, 'min': 1, '30': 1, 'valley': 1,
          'panther': 1, 'thus': 1, '14': 1, 'clearly': 1, 'httpifglobalwarmingisrealthenwhyisitcoldblogspotcom': 1,
          'adamcurry': 1, 'ki6amd': 1, 'nobama': 1, 'httptinyurlcomyhsp6tv': 1, 'gone': 1, 'stupidity': 1, 'go': 1,
          'boldly': 1, 'blunderto': 1, 'latest': 1, 'ipccs': 1, 'yidwithlid': 1, 'httptlgd7t756': 1, 'cont': 1,
          'scamhttptinyurlcomyf89oyf': 1, 'scientist': 1, 'crooked': 1, 'httpsupr1pjkit': 1}
total = {'climate': 646, 'global': 632, 'change': 615, 'warming': 591, 'link': 231, 'rt': 208, 'via': 81, 'us': 61,
         'report': 52, 'could': 49, 'science': 42, 'new': 42, 'green': 40, 'help': 38, 'news': 36, 'time': 32,
         'impacts': 32, 'snow': 31, 'energy': 31, 'tcot': 30, 'dc': 28, 'makes': 28, 'stop': 28, 'effects': 28,
         'gore': 26, 'world': 26, 'al': 25, 'weather': 25, 'arctic': 25, 'climatechange': 24, 'real': 24,
         'scientists': 24, 'air': 24, 'may': 24, 'blame': 22, 'winter': 20, 'day': 20, 'good': 19, 'health': 19,
         'bill': 19, 'obama': 18, 'like': 18, 'think': 18, 'thing': 18, 'one': 18, 'p2': 17, 'get': 17, 'sign': 17,
         'snowstorm': 17, 'causes': 17, 'great': 16, 'see': 16, 'people': 16, 'ever': 16, 'blizzards': 16, 'dont': 15,
         'hoax': 14, 'study': 14, 'due': 14, 'evidence': 14, 'another': 13, 'still': 13, 'p': 13, 'make': 13,
         'message': 13, 'volcano': 13, 'fighting': 13, 'made': 12, 'going': 12, 'across': 12, 'need': 12, 'far': 12,
         'getting': 12, 'way': 12, 'shows': 12, 'earthday': 12, 'o': 11, 'proof': 11, 'glacier': 11, 'coast': 11,
         'speed': 11, 'much': 10, 'gop': 10, 'planet': 10, 'heat': 10, 'live': 10, 'conference': 10, 'volcanoes': 10,
         'season': 10, 'natural': 10, 'act': 10, 'scientific': 9, 'climategate': 9, 'hey': 9, 'public': 9, 'bad': 9,
         '2': 9, 'storms': 9, 'video': 9, 'give': 9, 'decline': 9, 'pollution': 9, 'ground': 9, 'ice': 9, 'analysis': 9,
         'read': 9, 'raise': 9, 'making': 9, 'state': 9, 'spring': 9, 'causing': 9, 'skeptics': 8, 'man': 8,
         'believe': 8, 'know': 8, 'storm': 8, 'blizzard': 8, 'lake': 8, 'tell': 8, 'show': 8, 'love': 8, 'really': 8,
         'thought': 8, 'snowpocalypse': 8, 'would': 8, 'claims': 8, 'experts': 8, 'mother': 8, 'coal': 8, 'yet': 8,
         'research': 8, 'already': 8, 'tlot': 7, 'cold': 7, 'media': 7, 'fast': 7, 'using': 7, 'international': 7,
         'un': 7, 'globalwarming': 7, 'needs': 7, 'ask': 7, 'w': 7, 'demand': 7, 'back': 7, 'call': 7, 'right': 7,
         'bolivia': 7, 'support': 7, 'economic': 7, 'says': 7, 'agency': 7, 'keep': 6, 'teaparty': 6, 'lol': 6,
         'come': 6, 'someone': 6, 'doesnt': 6, 'major': 6, 'crisis': 6, 'mean': 6, 'senate': 6, 'watch': 6,
         'tsunami': 6, 'data': 6, 'caused': 6, 'billion': 6, 'ca': 6, 'working': 6, 'ft': 6, 'well': 6, 'isnt': 6,
         '30': 6, 'wont': 6, '20': 6, 'thats': 6, 'nasa': 6, 'federal': 6, 'days': 6, 'alaska': 6, 'solar': 6, 'im': 6,
         'imminent': 5, 'wheres': 5, 'consensus': 5, 'liberal': 5, 'please': 5, 'theory': 5, 'michael': 5, 'proves': 5,
         'graham': 5, 'also': 5, 'cant': 5, 'sense': 5, 'disaster': 5, 'got': 5, 'east': 5, 'peace': 5, 'buying': 5,
         'increasingly': 5, 'become': 5, 'either': 5, 'population': 5, 'times': 5, 'law': 5, 'sink': 5, 'debate': 5,
         'hard': 5, 'today': 5, 'story': 5, 'linked': 5, 'gets': 5, 'expert': 5, 'set': 5, 'years': 5, 'scientist': 5,
         'said': 5, 'two': 5, 'called': 5, 'valley': 5, 'evolution': 5, 'india': 5, 'mine': 4, 'snomg': 4, 'full': 4,
         'care': 4, 'washington': 4, 'otoolefan': 4, 'saying': 4, 'morning': 4, 'political': 4, 'calls': 4, 'main': 4,
         'u': 4, 'myth': 4, 'theres': 4, 'power': 4, 'bbc': 4, 'ha': 4, 'cut': 4, 'record': 4, 'wish': 4,
         'snowmageddon': 4, 'control': 4, 'house': 4, 'talks': 4, 'policy': 4, 'million': 4, 'strong': 4, 'adapt': 4,
         'mark': 4, '4': 4, 'society': 4, 'view': 4, 'reading': 4, 'leads': 4, 'little': 4, 'temperature': 4,
         'cooling': 4, 'heated': 4, 'basic': 4, 'latest': 4, 'newsbusters': 4, 'offers': 4, 'youtube': 4, 'noaa': 4,
         'deny': 4, '3': 4, 'massive': 4, 'e': 4, 'administration': 4, 'snowing': 3, 'jimdemint': 3, 'next': 3,
         'talk': 3, 'true': 3, 'houston': 3, 'gt': 3, 'suggest': 3, 'every': 3, 'tax': 3, 'property': 3, 'funding': 3,
         'truly': 3, 'since': 3, 'finally': 3, 'current': 3, 'war': 3, 'never': 3, 'idiots': 3, 'globe': 3, 'left': 3,
         'answer': 3, 'credits': 3, 'award': 3, 'fuel': 3, 'america': 3, 'attack': 3, 'near': 3, 'drudgereport': 3,
         'special': 3, 'challenges': 3, 'result': 3, 'immigration': 3, 'tonight': 3, 'discuss': 3, 'sighs': 3,
         'move': 3, 'stories': 3, 'oh': 3, 'go': 3, 'claim': 3, 'kerry': 3, 'official': 3, 'calling': 3, 'blamed': 3,
         'amazon': 3, 'thinks': 3, 'dead': 3, 'jobs': 3, 'old': 3, 'bringing': 3, 'member': 3, 'challenge': 3,
         'step': 3, 'cbs': 3, 'signs': 3, 'efforts': 3, 'idea': 3, 'pushing': 3, 'agenda': 3, 'switch': 3, 'facts': 3,
         'dare': 3, 'met': 3, 'tied': 3, 'families': 3, 'pic': 3, 'history': 3, 'claiming': 3, 'group': 3, 'use': 3,
         'american': 3, 'activists': 2, '29': 2, 'mag': 2, 'excuse': 2, 'stuff': 2, 'pen': 2, 'activist': 2, 'front': 2,
         'digg': 2, 'httpekwirecom': 2, 'ones': 2, 'paying': 2, 'joseph': 2, 'hows': 2, 'growth': 2, 'summer': 2,
         'vacation': 2, 'god': 2, 'probably': 2, 'average': 2, 'life': 2, 'gone': 2, 'truth': 2, 'disasters': 2,
         'creates': 2, 'mind': 2, 'v': 2, 'turn': 2, 'common': 2, 'distortions': 2, 'exposed': 2, 'theyre': 2,
         'anyone': 2, 'skepticism': 2, 'aimed': 2, 'computer': 2, 'speaks': 2, 'warning': 2, 'online': 2, 'polar': 2,
         'breaking': 2, 'send': 2, '8': 2, 'nature': 2, 'year': 2, 'trust': 2, 'opinion': 2, 'wind': 2, 'takes': 2,
         'president': 2, '28': 2, 'subject': 2, 'tale': 2, 'yes': 2, 'dying': 2, 'approach': 2, 'interview': 2,
         'businesses': 2, 'nyc': 2, 'unbelievable': 2, 'weird': 2, 'numbers': 2, 'frozen': 2, 'rules': 2, 'gbjoe': 2,
         'tolerant': 2, 'youd': 2, 'guilty': 2, 'crime': 2, 'httpbitlyaffkez': 2, 'according': 2, 'passes': 2,
         'icecovered': 2, 'questions': 2, 'try': 2, 'seems': 2, 'guess': 2, 'totally': 2, 'council': 2, 'chief': 2,
         'used': 2, 'seeks': 2, 'proponents': 2, 'politics': 2, 'httpbitly9trngu': 2, 'mmfa': 2, 'conservative': 2,
         'alarmism': 2, 'car': 2, 'per': 2, 'team': 2, 'failure': 2, 'pretending': 2}
total_existence = sum(existence.values())
total_denial = sum(denial.values())
total_total = sum(total.values())
outfile = open('classifications.csv', 'w')
index = 0

for tweet in tweets_clean:
    yscore = 1.0
    nscore = 1.0
    for word in tweet:
        if word in total:
            yscore = yscore * 10000 * ((existence.get(word, 0) / total.get(word, 1)) * (
                        (existence.get(word, 0) + denial.get(word, 0)) / total_total)) / (total_existence / total_total)
            nscore = nscore * 10000 * ((denial.get(word, 0) / total.get(word, 1)) * (
                        (existence.get(word, 0) + denial.get(word, 0)) / total_total)) / (total_denial / total_total)
        else:
            break
    if yscore > nscore:
        row_string = '{} {}'.format(index, 'Y')
    elif yscore < nscore:
        row_string = '{} {}'.format(index, 'N')
    else:
        row_string = '{} {}'.format(index, '???')
    index += 1
    outfile.write(row_string)
    outfile.write('\n')

# comparing to actual scores
outfile = open('answers.csv', 'w')
fileref = open('climate_test_answers.csv')
lines = fileref.readlines()
index = 0
lines_2 = []
for line in lines:
    words = line.strip().split(',')
    lines_2.append(words)
print(lines_2)
for line in lines_2:
    row_string = '{} {}'.format(index, line[1])
    outfile.write(row_string)
    outfile.write('\n')
    index += 1
